#### 1) Crear una matriz de una solo dimensión con numpy utilizando tupla

In [34]:
import numpy as np # Importamos la libreria "numpy" con el alias "np"
matriz1d = np.array((1, 2, 3, 4, 5))
dimension = matriz1d.ndim
print('--------------------------------------------')
print('La matriz de 1-D con Numpy usando una tupla:')
print(' ')
print(matriz1d)
print(' ')
print('La dimensión de la matriz: ', dimension)
print('--------------------------------------------')

--------------------------------------------
La matriz de 1-D con Numpy usando una tupla:
 
[1 2 3 4 5]
 
La dimensión de la matriz:  1
--------------------------------------------


#### 2) Crear una matriz de 2-D  con numpy

In [35]:
matriz2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
dimension = matriz2d.ndim
print('----------------------------')
print('La matriz de 2-D con Nunpy: ')
print(' ')
print(matriz2d)
print(' ')
print('Dimensión de la matriz: ', dimension)
print('----------------------------')

----------------------------
La matriz de 2-D con Nunpy: 
 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
 
Dimensión de la matriz:  2
----------------------------


#### 3) Acceder a elementos de un arreglo 2-D en Numpy

In [42]:
# Accedemos a un elemento individual
matriz2d_31 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
elemento = matriz2d_31[1][2] # Accediendo al elemento en la segunda fila y tercera columna
print('---------------------------------')
print('El elemento seleccionado es: ', elemento)
print('---------------------------------')

---------------------------------
El elemento seleccionado es:  6
---------------------------------


In [38]:
# Tanbién podemos acceder a una fila o columna completa
matriz2d_32 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
segunda_fila = matriz2d_32[1, :] # Accediendo a la segunda fila
tercera_columna = matriz2d_32[:, 2] # Accediendo a la tercera columna
print('-----------------------------------------')
print("Segunda fila: ", segunda_fila)
print("Tercera columna: ", tercera_columna)
print('-----------------------------------------')

-----------------------------------------
Segunda fila:  [4 5 6]
Tercera columna:  [3 6 9]
-----------------------------------------


#### 4) Obtener la forma de un arreglo Numpy 

In [23]:
import numpy as np
Arreglo = np.array([[1, 2, 3], [4, 5, 6]])
Tamanio = Arreglo.shape
print('--------------------------------------------------')
print('El orden del arreglo es: \n', Tamanio)
print('--------------------------------------------------')

--------------------------------------------------
El orden del arreglo es: 
 (2, 3)
--------------------------------------------------


#### 5)  Crear una matriz de orden 2x6 con numpy y mostrar el elemento de la fila 2 y columna 3

In [21]:
import numpy as np
Matriz = np.array([[1, 2, 3, 4, 5, 6], [7, 8, 9, 10, 11, 12]])
Elemento23 = Matriz[1,2]
print('--------------------------------------------------')
print('Matriz de orden 2x6:\n')
print(Matriz)
print(' ')
print('El elemneto de la fila 2 y columna 3:\n ', Elemento23)
print('--------------------------------------------------')

--------------------------------------------------
Matriz de orden 2x6:

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
 
El elemneto de la fila 2 y columna 3:
  9
--------------------------------------------------


#### 6) Mostrar mediante un ejemplo las diferencias entre una tupla y una lista 

In [25]:
# Mostramos las diferencias
# TUPLA
# Creación de una tupla
mi_tupla = (1, 2, 3)

# Intento de modificación de una tupla (produce un error)
mi_tupla[1] = 4


TypeError: 'tuple' object does not support item assignment

In [27]:
# LISTA
# Creación de una lista
mi_lista = [1, 2, 3]

# Modificación de una lista
mi_lista[1] = 4
print(mi_lista)

[1, 4, 3]


#### 7) Crear dos matrices, una de 2x2 y la otra 3x2, reemplazar el elemento de la fila 1 y columna 2 de la primera matriz con el elemento de la fila 2 y columna 1 de la segunda matriz

In [65]:
import numpy as np
# Matriz de orden 2x2
Matriz17 = np.array([[2, 4], [6, 8]])
# Matriz de orden 3x2
Matriz27 = np.array([[1, 3], [5, 7], [9, 11]])

Matriz17[0, 1] = Matriz27[1, 0] # Remplazando

print(Matriz17)

[[2 5]
 [6 8]]


#### 8) Mover dos elementos de una matriz a otra del ejercicio anterior

In [66]:
# Moviendo dos elementos
# Matriz de orden 2x2
Matriz17 = np.array([[2, 4], 
                     [6, 8]])
# Matriz de orden 3x2
Matriz27 = np.array([[1, 3], 
                     [5, 7], 
                     [9, 11]])

Matriz27[2,1] = Matriz17[1,1] 
Matriz27[1,0] = Matriz17[0,0] 

print('---------------------------')
print('Matriz17:')
print(Matriz17)
print('Matriz27:')
print(Matriz27)
print('---------------------------')

---------------------------
Matriz17:
[[2 4]
 [6 8]]
Matriz27:
[[1 3]
 [2 7]
 [9 8]]
---------------------------


#### 9) Intercambiar todos los elementos de las matrices del ejercio 7 si fuera posible

In [69]:
# Intercambiando todos elementos
# Cambiamos todos los elementos de la matriz17 a la matriz27
Matriz27[0,0] = Matriz17[0,0]
Matriz27[0,1] = Matriz17[0,1]
Matriz27[1,0] = Matriz17[1,0]
Matriz27[1,1] = Matriz17[1,1]

print('-------------------------------')
print('Matriz17: ')
print(Matriz17)
print('Matriz27: ')
print(Matriz27)
print('-------------------------------')

-------------------------------
Matriz17: 
[[2 4]
 [6 8]]
Matriz27: 
[[2 4]
 [6 8]
 [9 8]]
-------------------------------


In [70]:
# Cambiamos todos los elementos de la matriz27 a la matriz17
Matriz17[0,0] = Matriz27[0,0] 
Matriz17[0,1] = Matriz27[0,1] 
Matriz17[1,0] = Matriz27[1,0] 
Matriz17[1,1] = Matriz27[1,1]

print('-------------------------------')
print('Matriz27: ')
print(Matriz27)
print('Matriz17: ')
print(Matriz17)
print('-------------------------------')

-------------------------------
Matriz27: 
[[2 4]
 [6 8]
 [9 8]]
Matriz17: 
[[2 4]
 [6 8]]
-------------------------------


#### 10) Crear una matriz de 4x4 de tipo compleja y luego reeplazar el elemento de la fila 2 y columna 3 por un valor entero

In [90]:
import numpy as np
# Matriz de números complejos
MatrizComplejos = np.array([[1 + 2j, 2 + 3j, 3 + 4j, 4 + 5j],
                   [5 + 6j, 6 + 7j, 7 + 8j, 8 + 9j],
                   [9 + 10j, 10 + 11j, 11 + 12j, 12 + 13j],
                   [13 + 14j, 14 + 15j, 15 + 16j, 16 + 17j]], dtype=complex)
print('------------------------------------------')
print('Antes: ')
print(MatrizComplejos)
MatrizComplejos [1, 2] = 12 # Reeplazando el elemento de la fila 2 y columna 3 por un valor entero de 12.
print('------------------------------------------')
print('Despues: ')
print(MatrizComplejos)
print('------------------------------------------')

------------------------------------------
Antes: 
[[ 1. +2.j  2. +3.j  3. +4.j  4. +5.j]
 [ 5. +6.j  6. +7.j  7. +8.j  8. +9.j]
 [ 9.+10.j 10.+11.j 11.+12.j 12.+13.j]
 [13.+14.j 14.+15.j 15.+16.j 16.+17.j]]
------------------------------------------
Despues: 
[[ 1. +2.j  2. +3.j  3. +4.j  4. +5.j]
 [ 5. +6.j  6. +7.j 12. +0.j  8. +9.j]
 [ 9.+10.j 10.+11.j 11.+12.j 12.+13.j]
 [13.+14.j 14.+15.j 15.+16.j 16.+17.j]]
------------------------------------------
