![Imagen](https://miro.medium.com/max/815/1*S9cur9wmGVv2bg7b6wlscg.jpeg)

https://numpy.org/

In [155]:
#Importando la libería
import numpy as np


# 1) Introducccion

**NumPy** es una librería de Python especializada en el cálculo numérico y el análisis de datos, especialmente para un gran volumen de datos.

Incorpora una nueva clase de objetos llamados **arrays** que permite representar colecciones de datos de un mismo tipo en varias dimensiones, y funciones muy eficientes para su manipulación.

+ un poderoso objeto de arreglo N-dimensional
+ herramientas para integrar código en C/C++ y Fortran
+ útiles capacidades de álgebra lineal, transformación de Fourier y números aleatorios



# 2) Array

son la forma principal de almacenar datos utilizando la biblioteca NumPy. Son similares a las listas normales en Python, pero tienen la ventaja de ser más rápidas (hasta 50 veces más) y tener más métodos integrados.

## 2.1 Creación de arrays
* lista y tuplas de Python.
* usando funciones que están dedicadas a generar matrices numpy, como `arange`, `linspace`, etc.
 
 

### 2.1.1 Creación de arrays utilizando lista y tuplas de Python.


###  *¿Qué es una lista?* 

#### Ejemplo 1


La lista se representa mediante corchetes  

In [169]:
[2,4,100,59]

In [170]:
lista1=[2,4,100,59]
lista1

In [171]:
lista2=['Data',1,2,'Analítica']
lista2

In [159]:
lista2[0]='analítica'

In [172]:
lista2

### ¿Qué es una tupla? 

#### Ejemplo 2 

La tupla se representa mediante parentesis 

In [173]:
tupla1=('Data',1,2,'Analítica')
tupla1

In [163]:
# tupla1[0]='analítica'

<p style="color:blue"> OJO 

<p style="color:purple"> las tuplas son más rápidas que las listas
    
<p style="color:purple"> Las tuplas hacen que el código esté a salvo de cualquier modificación accidental. Si se necesita un dato en un programa que se supone que no debe cambiarse, entonces es mejor ponerlo en 'tuplas' que en 'lista'.
    
<p style="color:purple">Las tuplas se pueden usar como claves de diccionario si contienen valores inmutables como cadenas, números u otra tupla. Las 'listas' nunca se pueden usar como claves de diccionario, ya que las 'listas' son mutables.

#### para crear un array se utilizará np.array 


#### Ejemplo 3 

Un vector, utilizando una lista 

In [174]:
vector1=np.array([2,4,6,87])
vector1

#### Ejemplo 4 

Una matriz, utilizamos una listas dentro de otra lista

In [175]:
matriz1=np.array([[1,2,3],[5,8,5]])
matriz1

#### Ejemplo 5 

Un vector, utilizando tuplas

In [168]:
vector2=np.array((3,7,9))
vector2

###### Se observa que los vectores y matrices creadas anteriormente son del mismo tipo 

In [167]:
type(vector1),type(vector2)

##### Identificando las dimensiones  shape   y la cantidad de elementos size 


In [14]:
vector2.shape

(3,)

In [40]:
matriz2.shape

(3, 3)

In [14]:
matriz2.size

9

#### Diferencias entre lista y array 

| Lista | Array |
|:- |:-|
| Puede consistir en elementos que pertenecen a diferentes tipos de datos | Solo consta de elementos que pertenecen al mismo tipo de datos |
| No es necesario importar explícitamente un módulo para la declaración | Necesidad de importar explícitamente un módulo para la declaración | 
|No se pueden manejar directamente las operaciones aritméticas|Puede manejar directamente operaciones aritméticas|
|Se puede anidar para contener diferentes tipos de elementos|Debe contener todos los elementos anidados del mismo tamaño|
|Preferido para una secuencia más corta de elementos de datos|Preferido para una secuencia más larga de elementos de datos|
|Una mayor flexibilidad permite una fácil modificación (adición, eliminación) de datos|Menos flexibilidad ya que la adición, la eliminación tiene que hacerse en cuanto a elementos|
|La lista completa se puede imprimir sin ningún bucle explícito|Se debe formar un bucle para imprimir o acceder a los componentes de la matriz|
|Consume mayor memoria para añadir elementos fácilmente|Comparativamente más compacto en tamaño de memoria|




##### Se puede especificar el tipo de dato del array indicando el argumento dtype

In [184]:
matriz = np.array([[1, 2], [3, 4]], dtype=float)
matriz

#### Los tipos de datos más comunes
int, float, complex, bool, object, etc.

#### Ejemplo 6 

Cambiando el elemento de la fila uno y columna uno por el valor de 3

In [185]:
matriz[0,0]=3
matriz

#### Ejemplo 7 

Intercambio de un valor float por un complex

In [188]:
# #¿ que sucede?
# matriz[0,0]=2+3j
# matriz

In [192]:
matriz=np.array([[3,2],[4,6]],dtype=complex)
matriz

In [193]:
matriz[0,0]=2+3j
matriz

#### Se puede cambiar el tipo de datos


#### Ejemplo 8 

Intercambiando un entero por un complejo 

In [25]:
matriz=np.array([[1,2,3,4],[8,1,2,5]])
matriz

array([[1, 2, 3, 4],
       [8, 1, 2, 5]])

In [22]:
matriz.astype('complex')

array([[1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j],
       [8.+0.j, 1.+0.j, 2.+0.j, 5.+0.j]])

### 2.1.2 Creación de matrices utilizando funciones de numpy

#### np.arange(start, stop, step) step-->determina el tamaño de los pasos    

#### Ejemplo 9 

Especificando todos los parámetros

In [23]:
np.arange(2,12,3)

array([ 2,  5,  8, 11])

#### Ejemplo 10 

Especificando solo dos parámetros 

In [24]:
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

#### Ejemplo 11 

Especificando solo un parámetro

In [34]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

##### Ejemplo 12  

Hallando los multiplos de 3 comprendidos entre 5 y 27

In [196]:
np.arange(6,27,3)

array([ 6,  9, 12, 15, 18, 21, 24])

#### np.linspace(start, stop, num) num-->especifica la cantidad de numeros


#### Ejemplo 13 

3 números que van desde 2 al 12 

In [9]:
np.linspace(2,12,3)

array([ 2.,  7., 12.])

#### np.logspace(start, stop, num, base) base---->especifica la base del logaritmo



#### Ejemplo 14 

Un Array con números logaritmicos

In [43]:
np.logspace(2,9,7,base=3)

array([9.00000000e+00, 3.24252978e+01, 1.16822215e+02, 4.20888346e+02,
       1.51638111e+03, 5.46323433e+03, 1.96830000e+04])

$\log_{a}(x)=y \iff a^{y}=x$

$\log_{3}(x)=2 \iff 3^{2}=9\text{        ,            } \log_{3}(x)=9 \iff 3^{9}=19683$

##### generando valores aleatorios  

In [71]:
import random

##### Ejemplo 15  

Hallando valores aleatorios entre 0 y 1

In [129]:
np.random.seed(5) #estableciendo una semilla
np.random.random([2,4]) #genera valores float entre 0 y 1

array([[0.22199317, 0.87073231, 0.20671916, 0.91861091],
       [0.48841119, 0.61174386, 0.76590786, 0.51841799]])

#### Ejemplo 16  

Hallando valores aleatorios que provienen de una distribución normal estandar

https://numpy.org/doc/stable/reference/random/generated/numpy.random.randn.html

In [29]:
np.random.seed(12)
np.random.randn(2, 4)

array([[ 0.47298583, -0.68142588,  0.2424395 , -1.70073563],
       [ 0.75314283, -1.53472134,  0.00512708, -0.12022767]])

#### matriz diagonal 

#### Ejemplo 17 

matriz diagonal

In [133]:
diag_matrix = np.diag([2, 2, 6, 4, 4])
diag_matrix

array([[2, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 6, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 4]])

##### matriz de ceros y unos 

##### Ejemplo 18 

Matriz de ceros  

In [141]:
zeros_matrix = np.zeros((10, 5))
zeros_matrix

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

#### Ejemplo de 19 

Matriz de unos

In [151]:
ones_matrix=np.ones([4,3])
ones_matrix

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## 2.2 Indexing y slicing 

### 2.2.1 Indexing

Para acceder a los elementos de un array se utiliza los corchetes  [  ]

<p style="color:blue"> RECORDAR 

 <p style="color:Purple"> La indexación siempre comienza con 0. Por lo tanto, el primer elemento de una lista está presente en el índice 0, no en 1.
     
 <p style="color:Purple;"> la indexación negativa significa que el índice de -1 se refiere al último elemento, -2 al penúltimo elemento y así sucesivamente.
 
     


In [32]:
vector=[2,6,9,89,13]

In [38]:
matriz=np.array([[1,3,5,9],[2,4,6,8],[2,3,5,7]])
matriz

array([[1, 3, 5, 9],
       [2, 4, 6, 8],
       [2, 3, 5, 7]])

#### Ejemplo 20 

Encontrando el segundo elemento del vector  

In [31]:
#un vector es de una sola dimensión, por lo tanto un index 
vector[1]

6

#### Ejemplo 21 

Encontrando el elemento de la fila 3 y columna 2 de la matriz

In [41]:
#la matriz es de dos dimensiones, por lo tanto dos index  
matriz[2,1]

3

#### Ejemplo 22 

Econtrando toda una fila de una matriz

In [42]:
matriz[1,:]

array([2, 4, 6, 8])

#### Ejemplo 23 

Encontrando toda una columna

In [43]:
matriz[:,2]

array([5, 6, 5])

#### Ejemplo 24 

Modificando el valor de un elemento de una matriz

In [44]:
matriz[0,0]=30

In [45]:
matriz

array([[30,  3,  5,  9],
       [ 2,  4,  6,  8],
       [ 2,  3,  5,  7]])

#### Ejemplo 25   

Modificando todos los elemntos de una fila de la matriz

In [46]:
matriz[2,:]=7

In [47]:
matriz

array([[30,  3,  5,  9],
       [ 2,  4,  6,  8],
       [ 7,  7,  7,  7]])

### 2.2.2 Index slicing

`matriz[inicio:fin:paso]`

#### Ejemplo 25 

In [10]:
x=np.array([2,3,5,7,11,13])
x

array([ 2,  3,  5,  7, 11, 13])

In [17]:
x[1:2]

array([3])

In [52]:
x[1:5]

array([ 3,  5,  7, 11])

In [54]:
x[::2] 

array([ 2,  5, 11])

# Caso aplicativo Python Vs Numpy

### Multiplicación de elementos uno a uno de dos vectores o listas 

In [2]:
import numpy as np
tamaño = 10000
lista1 = np.arange(tamaño)
lista2 = np.arange(tamaño)

In [3]:
import time 

### 1) Con una lista y for   

In [4]:
tiempo_inicial = time.time()
tiempo_inicial

1676678851.2272503

In [5]:
tiempo_inicial = time.time()
resultado1 = []
for i in range(0,tamaño):
    var1 = lista1[i]*lista2[i]
    resultado1.append(var1)
tiempo_final = time.time()
t1 = tiempo_final - tiempo_inicial
print('Se demora', t1, 'en segundos')

Se demora 0.0059969425201416016 en segundos


### 2)  Con una lista y for en una linea

In [6]:
tiempo_inicial = time.time()
resultado2 = [(a*b) for a,b in zip(lista1,lista2)]
tiempo_final = time.time()
t2 = tiempo_final - tiempo_inicial
print('Se demora', t2, 'en segundos')

Se demora 0.002000093460083008 en segundos


### 3) Con np. array 

In [7]:
vector1 = np.arange(tamaño)
vector1

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [8]:
vector2 = np.arange(tamaño)
vector2

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [9]:
tiempo_inicial = time.time()
resultado3 = vector1*vector2
tiempo_final = time.time()
t3 = tiempo_final - tiempo_inicial
print('Se demora', t3, 'en segundos')

Se demora 0.00099945068359375 en segundos
