In [4]:
import numpy as np
import pandas as pd

#### 1) Crear una matriz de una solo dimensión con numpy utilizando tupla

In [2]:
x=np.array((2,3,6,7,9,4,6,7,1,9))
x

array([2, 3, 6, 7, 9, 4, 6, 7, 1, 9])

In [3]:
len(x)

10

#### 2) Crear una matriz de 2-D  con numpy

In [4]:
y=np.array([[2,3,4,5,67],[1,3,4,6,7]])
y

array([[ 2,  3,  4,  5, 67],
       [ 1,  3,  4,  6,  7]])

#### 3) Acceder a elementos de un arreglo 2-D en Numpy

In [5]:
y=np.array([[2,3,4,5,67],[1,3,4,6,7]])
y

array([[ 2,  3,  4,  5, 67],
       [ 1,  3,  4,  6,  7]])

In [6]:
#Elemento de la fila 2 y columna 3
y[1][2]

4

In [7]:
#Elemento de la fila 1 y columna 5
y[0][4]

67

#### 4) Obtener la forma de un arreglo Numpy 

In [8]:
y.shape

(2, 5)

#### 5)  Crear una matriz de orden 2x6 con numpy y mostrar el elemento de la fila 2 y columna 3

In [9]:
x=np.array([[14,7,98,1,2,9],[7,8,9,4,6,3]])
x

array([[14,  7, 98,  1,  2,  9],
       [ 7,  8,  9,  4,  6,  3]])

In [10]:
x[1][2]

9

#### 6) Mostrar mediante un ejemplo las diferencias entre una tupla y una lista 

In [11]:
#lista
x=[2,4,6,8]

#tupla
y=(3,6,9)

In [12]:
#se puede modificar los elementos de una lista
x[1]=20

In [13]:
x

[2, 20, 6, 8]

In [14]:
#no se puede modificar los elementos de una tupla
y[1]=20

TypeError: 'tuple' object does not support item assignment

#### 7) Crear dos matrices, una de 2x2 y la otra 3x2, reemplazar el elemento de la fila 1 y columna 2 de la primera matriz con el elemento de la fila 2 y columna 1 de la segunda matriz

In [15]:
x=np.array([[1,3],[6,8]])
x

array([[1, 3],
       [6, 8]])

In [16]:
y=np.array([[1,3],[6,8],[9,5]])
y

array([[1, 3],
       [6, 8],
       [9, 5]])

In [17]:
x[0][1]=y[1][0]

In [18]:
x

array([[1, 6],
       [6, 8]])

#### 8) Mover dos elementos de una matriz a otra del ejercicio anterior

In [19]:
x=np.array([[1,3],[6,8]])
x

array([[1, 3],
       [6, 8]])

In [20]:
y=np.array([[2,4],[7,5],[9,5]])
y

array([[2, 4],
       [7, 5],
       [9, 5]])

In [21]:
x[0][0]=y[1][1]
x[1][0]=y[2][0]

In [22]:
x

array([[5, 3],
       [9, 8]])

#### 9) Intercambiar todos los elementos de las matrices del ejercio 7 si fuera posible

In [23]:
x=np.array([[1,3],[6,8]])
x

array([[1, 3],
       [6, 8]])

In [24]:
y=np.array([[2,4],[7,5],[9,5]])
y

array([[2, 4],
       [7, 5],
       [9, 5]])

In [25]:
z=np.copy(x)
x[0][0]=y[0][0]
x[0][1]=y[0][1]
x[1][0]=y[1][0]
x[1][1]=y[1][1]

y[0][0]=z[0][0]
y[0][1]=z[0][1]
y[1][0]=z[1][0]
y[1][1]=z[1][1]


In [26]:
x

array([[2, 4],
       [7, 5]])

In [27]:
y

array([[1, 3],
       [6, 8],
       [9, 5]])

#### 10) Crear una matriz de 4x4 de tipo compleja y luego reemplazar el elemento de la fila 2 y columna 3 por un valor entero

In [5]:
x=np.array([[2,3,4,5],[0,5,7,9],[9,5,4,1]],dtype=complex)
x

array([[2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j],
       [0.+0.j, 5.+0.j, 7.+0.j, 9.+0.j],
       [9.+0.j, 5.+0.j, 4.+0.j, 1.+0.j]])

In [6]:
x[1][2]=2

In [7]:
x

array([[2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j],
       [0.+0.j, 5.+0.j, 2.+0.j, 9.+0.j],
       [9.+0.j, 5.+0.j, 4.+0.j, 1.+0.j]])