In [1]:
import pandas as pd

## Problema 1

Crear una matriz de orden 3x3 y hallar el determiante con numpy, además aplicar el método de cofactores utilizando el jupyter como claculadora, es decir hacerlo celda por celda

In [71]:
# Importar libreria
import numpy as np
# Creamos la matriz de orden 3x3
matriz = np.array([[1, 2, 3], 
                   [4, 5, 6], 
                   [7, 8, 9]])
# Imprimir la matriz.
print(matriz)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [72]:
# Calcular el determinate.
determinante = np.linalg.det(matriz)
# Imprimir el determinante.
print(determinante)

6.66133814775094e-16


## Problema 2

Hacer una función que resuelva el problema anterior

In [79]:
import numpy as np

In [80]:
 def determinante(matriz):
    '''
    Creamos una función para calcular el determinante de
    una matriz de orden n.
    '''
    n = len(matriz)
    
    if n == 1:
        return matriz[0][0]
    
    det = 0
    
    for j in range(n):
        submatriz = []
        for i in range(1, n):
            fila = []
            for k in range(n):
                if k != j:
                    fila.append(matriz[i][k])
            submatriz.append(fila)
        det += ((-1) ** j) * matriz[0][j] * determinante(submatriz)
    
    return det

In [81]:
def cofactores(matriz):
    '''
    Creamos una función para calcular la matriz de cofactores
    de una matriz de orden n.
    '''
    n = len(matriz)
    cofactores = np.zeros((n, n))
    
    for i in range(n):
        for j in range(n):
            submatriz = []
            for p in range(n):
                fila = []
                for q in range(n):
                    if p != i and q != j:
                        fila.append(matriz[p][q])
                if fila:
                    submatriz.append(fila)
            cofactores[i][j] = ((-1) ** (i + j)) * determinante(submatriz)
    
    return cofactores

In [82]:
'''
Para calcular el determinante usando el método de cofactores, simplemente
multiplicamos los elementos de la primera fila de la matriz por sus respectivos
cofactores y los sumamos.
'''
matriz = np.array([[1, 2, 3], 
                   [4, 5, 6], 
                   [7, 8, 9]])
C = cofactores(matriz)
determinante = 0

for j in range(len(matriz)):
    determinante += matriz[0][j] * C[0][j]
    
print(determinante)

0.0


## Problema 3

Hacer una función que resuelva el problema uno con el método de Sarrus 

In [83]:
'''
Para hallar el determinante de una matriz de orden 3 por 3 usando el
método de Sarrus en Python, se puede implementar una función que tome
como entrada la matriz y devuelva su determinante. El método de Sarrus
consiste en escribir la matriz de forma expandida, añadiendo las dos 
primeras columnas al final. A continuación, se suman los productos 
diagonales de izquierda a derecha y se restan los productos diagonales
de derecha a izquierda. El resultado obtenido es el determinante de la matriz.
A continuación, se muestra una posible implementación de esta función en Python:
'''

def determinante_sarrus(matriz):
    if matriz.shape != (3, 3):
        return "La matriz debe ser de orden 3 por 3"
    expandida = np.hstack((matriz, matriz[:,:2]))
    prod_diag_izq_der = expandida[0,0]*expandida[1,1]*expandida[2,2] + expandida[0,1]*expandida[1,2]*expandida[2,0] + expandida[0,2]*expandida[1,0]*expandida[2,1]
    prod_diag_der_izq = expandida[0,2]*expandida[1,1]*expandida[2,0] + expandida[0,0]*expandida[1,2]*expandida[2,1] + expandida[0,1]*expandida[1,0]*expandida[2,2]
    determinante = prod_diag_izq_der - prod_diag_der_izq
    return determinante


In [ ]:
'''
Para utilizar esta función, se debe pasar la matriz como un objeto NumPy de la siguiente manera:
'''

In [84]:
import numpy as np

matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
determinante = determinante_sarrus(matriz)
print(f"El determiante es: {determinante}")


El determiante es: 0


## Problema 4

Replicar las 8 propiedades vistas en clase para los determinantes mediante un ejemplo 

* Propiedad 1

Si $A$ una matriz de orden 3x3

$$
A = \left(\begin{matrix}
{a1 \quad a2 \quad a3}\\
{b1 \quad b2 \quad b3}\\
{c1 \quad c2 \quad c3}\\
\end{matrix}\right)_{3\times 3}
$$
La propiedad 1 nos dice que $|A| = |A^{T}|$, es decir
$$
\begin{vmatrix}
{a1 \quad a2 \quad a3}\\
{b1 \quad b2 \quad b3}\\
{c1 \quad c2 \quad c3}\\
\end{vmatrix} =
\begin{vmatrix}
{a1 \quad b1 \quad c1}\\
{a2 \quad b2 \quad c2}\\
{a3 \quad b3 \quad c3}\\
\end{vmatrix}
$$

In [18]:
# Importar la libreria NumPy
import numpy as np

In [26]:
# Creamos una matriz "A1" de orden 3x3 (3 filas y 3 columnas)
A1 = np.array([
    [3, -2, 6],
    [2, 1, -4],
    [-3, 2, 7]
])
A1

array([[ 3, -2,  6],
       [ 2,  1, -4],
       [-3,  2,  7]])

In [21]:
# Transpuesta de A1 (TA1)
TA1 = A1.T
print(f"La transpuesta de A1 es :\n {TA1}")

La transpuesta de A1 es :
 [[ 3  2 -3]
 [-2  1  2]
 [ 6 -4  7]]


In [22]:
# Determinante de la transpuesta de A1 (DTA1)
DTA1 = np.linalg.det(TA1)
print(f"El determinante de la transpuesta de A1 es: \n {DTA1}")

El determinante de la transpuesta de A1 es: 
 90.99999999999997


In [23]:
# Determinante de A1 (DA1)
DA1 = np.linalg.det(A1)
print(f"El determinate de A1 es: \n {DA1}")

El determinate de A1 es: 
 90.99999999999997


In [40]:
# La propiedad 1 se cumple. Por lo tanto, el "DTA1" y "DA1" son iguales.
print(f"El DTA1 = {DTA1} y DA1 = {DA1} son iguales.")

El DTA1 = 90.99999999999997 y DA1 = 90.99999999999997 son iguales.


* Propiedad 2

Si todos los elementos de una fila (o columna) son ceros, entonces el determinante es cero.

$$
\begin{vmatrix}
{a1 \quad a2 \quad a3}\\
{0  \quad 0  \quad 0}\\
{c1 \quad c2 \quad c3}\\
\end{vmatrix}
= 
\begin{vmatrix}
{a1 \quad 0 \quad a3}\\
{b1 \quad 0 \quad b3}\\
{c1 \quad 0 \quad c3}\\
\end{vmatrix} = 0
$$



In [ ]:
# Importar la libreria NumPy
import numpy as np

In [32]:
# Creamos una matriz "A2_1" de orden 3x3 (3 filas y 3 columnas)
#---- Todos los elementos de la fila 1 son ceros.
A2_1 = np.array([
    [0, 0, 0],
    [2, 1, -4],
    [-3, 2, 7]
])
A2_1

array([[ 0,  0,  0],
       [ 2,  1, -4],
       [-3,  2,  7]])

In [37]:
# Determinate de "A2_1"
DA2_1 = np.linalg.det(A2_1)
print(f"El determiante de A2_1 es: \n {DA2_1}")

El determiante de A2_1 es: 
 0.0


In [38]:
# Creamos una matriz "A2_2" de orden 3x3 (3 filas y 3 columnas)
#---- Todos los elementos de la columna 1 son ceros.
A2_2 = np.array([
    [0, -2, 6],
    [0, 1, -4],
    [0, 2, 7]
])
A2_2

array([[ 0, -2,  6],
       [ 0,  1, -4],
       [ 0,  2,  7]])

In [39]:
# Determinate de "A2_2"
DA2_2 = np.linalg.det(A2_2)
print(f"El determiante de A2_2 es: \n {DA2_2}")

El determiante de A2_2 es: 
 0.0


In [41]:
# La propiedad 2 se cumple. Por lo tanto, el determiante de "A2_1" y "A2_2" es cero.
print(f"El determiante de A2_1 = {DA2_1} y A2_2 = {DA2_2}")

El determiante de A2_1 = 0.0 y A2_2 = 0.0


* Propiedad 3

Si todos los elementos de una fila (o columna) son proporcionales (idénticos) a los elementos de alguna otra fila (o columna), entonces el determinante es cero.

$$
\begin{vmatrix}
{a1 \quad ka2 \quad a3}\\
{b1 \quad kb2 \quad b3}\\
{c1 \quad kc2 \quad c3}\\
\end{vmatrix} = 0
$$

In [42]:
# Importar la libreria NumPy
import numpy as np

In [44]:
# Creamos una matriz "A3" de orden 3x3 (3 filas y 3 columnas)

A3 = np.array([
    [2, 0, 6],
    [5, 1, 15],
    [7, 2, 21]
])
A3

array([[ 2,  0,  6],
       [ 5,  1, 15],
       [ 7,  2, 21]])

In [52]:
# Determinate de "A3"
DA3 = np.linalg.det(A3)
#DA3 = round(DA3,2)
print(f"El determiante de A3 es: \n {DA3}")

El determiante de A3 es: 
 -7.105427357600985e-15


In [53]:
# La propiedad 3 se cumple. Por lo tanto, el determinante de A3 es cero.
print(f"El determiante de A3 es : {DA3}")

El determiante de A3 es : -7.105427357600985e-15


* Propiedad 4

El intercambio de dos filas (o columnas) `cualesquiera` del determinante cambia su signo.

* `Recomendación`

Si se intercambian dos filas o dos columnas `continuas` en un determinante, 
el valor de este cambia de signo.

$$
\begin{vmatrix}
{a1 \quad a2 \quad a3}\\
{b1 \quad b2 \quad b3}\\
{c1 \quad c2 \quad c3}\\
\end{vmatrix}
= -
\begin{vmatrix}
{b1 \quad b2 \quad b3}\\
{a1 \quad a2 \quad a3}\\
{c1 \quad c2 \quad c3}\\
\end{vmatrix}
$$


In [88]:
# Importar la libreria NumPy
import numpy as np

In [89]:
# Creamos una matriz "A4_sc" de orden 3x3 (3 filas y 3 columnas)
A4_sc = np.array([
    [2, 0, 3],
    [5, 1, 5],
    [7, 2, 11]
])
A4_sc

array([[ 2,  0,  3],
       [ 5,  1,  5],
       [ 7,  2, 11]])

In [90]:
# Determinate de "A4_sc"
DA4_sc = np.linalg.det(A4_sc)
DA4_sc
print(f"El determiante de A4 sin cambios es: \n {DA4_sc}")

El determiante de A4 sin cambios es: 
 10.999999999999991


In [91]:
# Intercambiar la fila 1 con la fila 2
A4_sc[[0,1]] = A4_sc[[1,0]] # Cambio de las filas en la matriz "A4".
A4_cc = A4_sc

In [92]:
# Entonces, el determinate de "A4_cc" con las filas intercambiadas es
DA4_cc = np.linalg.det(A4_cc)
print(f"El determiante de A4 es: \n {DA4_cc}")

El determiante de A4 es: 
 -10.999999999999991


In [93]:
# La propiedad 4 se cumple. Por lo tanto, el determinante de A4_sc cambia de signo.
print(f"El determiante de A4_sc = {DA4_sc} y el A4_cc= {DA4_cc}")

El determiante de A4_sc = 10.999999999999991 y el A4_cc= -10.999999999999991


* Propiedad 5

Si $B$ es una Matriz formada sumando el múltiplo de cualquier fila a otra fila, entonces

$$
det(X) = det(B)
$$

In [94]:
# Importar la libreria NumPy
import numpy as np

In [98]:
# Creamos una matriz "X" de orden 3x3 (3 filas y 3 columnas)
X = np.array([
    [3, 0, 3],
    [-2, 1, 5],
    [8, 2, 11]
])
X

array([[ 3,  0,  3],
       [-2,  1,  5],
       [ 8,  2, 11]])

In [99]:
# Determinate de "X" (DX)
DX = np.linalg.det(X)
print(f"El determiante de X es: \n {DX}")

El determiante de X es: 
 -32.999999999999986


In [100]:
# Creamos una matriz "B" de orden 3x3
# ------ Sumando 2 veces de la primera columna a la segunda
B = np.array([
    [3, 6, 3],
    [-2, -3, 5],
    [8, 18, 11]
])
B

array([[ 3,  6,  3],
       [-2, -3,  5],
       [ 8, 18, 11]])

In [101]:
# Determinate de "B" (DB)
DB = np.linalg.det(B)
print(f"El determiante de X es: \n {DB}")

El determiante de X es: 
 -32.999999999999986


In [106]:
# La propiedad 5 se cumple. Por lo tanto, el det(X) = det(B).
print(f"El determiante de X es igual a: {DX}")
print(f"El determiante de B es igual a: {DB}")

El determiante de X es igual a: -32.999999999999986
El determiante de B es igual a: -32.999999999999986


* Propiedad 6

$$
\begin{vmatrix}
{\lambda a_{11}\quad\cdots\quad \lambda a_{1n}}\\
{a_{21}\quad\cdots\quad a_{2n}}\\
{\vdots \quad \vdots}\\
{a_{n1}\quad\cdots\quad a_{nn}}\\
\end{vmatrix}=
\lambda \begin{vmatrix}
{a_{11}\quad\cdots\quad a_{1n}}\\
{a_{21}\quad\cdots\quad a_{2n}}\\
{\vdots \quad \vdots}\\
{a_{n1}\quad\cdots\quad a_{nn}}\\
\end{vmatrix}
$$

In [124]:
# Importar la libreria NumPy
import numpy as np

In [125]:
# Creamos una matriz "A6" de orden 3x3 (3 filas y 3 columnas)
A6 = np.array([
    [4, 2, 3],
    [2, -1, 5],
    [3, 5, -4]
])
A6

array([[ 4,  2,  3],
       [ 2, -1,  5],
       [ 3,  5, -4]])

In [126]:
# Determinate de "A6" (DA6)
DA6 = np.linalg.det(A6)
print(f"El determiante de A6 es: \n {DA6}")

El determiante de A6 es: 
 0.9999999999999969


In [127]:
# Multiplicamos a la primera fila por un lambda = 3
A6[0] = A6[0]*3
A6_clambda = A6
A6_clambda 

array([[12,  6,  9],
       [ 2, -1,  5],
       [ 3,  5, -4]])

In [131]:
# Determinate de "A6_clambda" (DA6_clambda)
DA6_clambda = np.linalg.det(A6_clambda)
print(f"El determiante de A6_clambda es: \n {DA6_clambda}")

El determiante de A6_clambda es: 
 2.9999999999999902


In [132]:
# Determinante de a "A6_clambda" es igual a lambda por el DA6
DA6_plambda = 3*DA6
DA6_plambda

2.9999999999999907

In [133]:
# La propiedad 6 se cumple. Por lo tanto, el "DA6_clambda" es igual a lambda por el "DA6".
print(f"El determiante de 'DA6_clambda' = {DA6_clambda} es igual a 'DA6_plambda' = {DA6_plambda}")

El determiante de 'DA6_clambda' = 2.9999999999999902 es igual a 'DA6_plambda' = 2.9999999999999907


* Propiedad 7
$$
\begin{vmatrix}
{\lambda a_{11}\quad\cdots\quad  a_{1n}}\\
{\lambda a_{21}\quad\cdots\quad a_{2n}}\\
{\vdots \quad \vdots}\\
{\lambda a_{n1}\quad\cdots\quad a_{nn}}\\
\end{vmatrix}=
\lambda \begin{vmatrix}
{a_{11}\quad\cdots\quad a_{1n}}\\
{a_{21}\quad\cdots\quad a_{2n}}\\
{\vdots \quad \vdots}\\
{a_{n1}\quad\cdots\quad a_{nn}}\\
\end{vmatrix}
$$

In [136]:
# Importar la libreria NumPy
import numpy as np

In [158]:
# Creamos una matriz "A7" de orden 3x3 (3 filas y 3 columnas)
A7 = np.array([
    [4, 2, 3],
    [2, -1, 5],
    [3, 5, -4]
])
A7

array([[ 4,  2,  3],
       [ 2, -1,  5],
       [ 3,  5, -4]])

In [159]:
# Determinate de "A7" (DA7)
DA7 = np.linalg.det(A7)
print(f"El determiante de A7_colum es: \n {DA7}")

El determiante de A7_colum es: 
 0.9999999999999969


In [156]:
A7[0][0] = A7[0][0]*5
A7[1][0] = A7[1][0]*5
A7[2][0] = A7[2][0]*5
A7_colum = A7
A7_colum

array([[20,  2,  3],
       [10, -1,  5],
       [15,  5, -4]])

In [157]:
# Determinate de "A7_colum" (DA7_colum)
DA7_colum = np.linalg.det(A7_colum)
print(f"El determiante de A7_colum es: \n {DA7_colum}")

El determiante de A7_colum es: 
 4.9999999999999805


In [164]:
# Lambda = 5 por el determinante de A7 
DA7_lambda = 5*DA7
DA7_lambda

4.999999999999984

In [165]:
# La propiedad 7 se cumple. Por lo tanto, el "DA7_colum" es igual a lambda por el "DA7".
print(f"El determiante de 'DA7_colum' = {DA7_colum} es igual a lambda por el 'DA7' = {DA7_lambda}")

El determiante de 'DA7_colum' = 4.9999999999999805 es igual a lambda por el 'DA7' = 4.999999999999984


* Propiedad 8
$$
\begin{vmatrix}
{\lambda a_{11}\quad\cdots\quad \lambda a_{1n}}\\
{\lambda a_{21}\quad\cdots\quad  \lambda a_{2n}}\\
{\vdots \quad \vdots}\\
{\lambda a_{n1}\quad\cdots\quad \lambda a_{nn}}\\
\end{vmatrix}=
\lambda^{n} \begin{vmatrix}
{a_{11}\quad\cdots\quad a_{1n}}\\
{a_{21}\quad\cdots\quad a_{2n}}\\
{\vdots \quad \vdots}\\
{a_{n1}\quad\cdots\quad a_{nn}}\\
\end{vmatrix} 
$$


In [ ]:
# Importar la libreria NumPy
import numpy as np

In [178]:
# Creamos una matriz "A8" de orden 3x3 (3 filas y 3 columnas)
A8 = np.array([
    [5, -12, 3],
    [7, -1, 11],
    [13, 5, -4]
])
A8

array([[  5, -12,   3],
       [  7,  -1,  11],
       [ 13,   5,  -4]])

In [179]:
# Determinate de "A8" (DA8)
DA8 = np.linalg.det(A8)
print(f"El determiante de A8 es: \n {DA8}")

El determiante de A8 es: 
 -2162.999999999999


In [180]:
# Multiplicando a todos los elementos por lambda = 2
A8[0] = A8[0]*2
A8[1] = A8[1]*2
A8[2] = A8[2]*2
A8_1 = A8
A8_1

array([[ 10, -24,   6],
       [ 14,  -2,  22],
       [ 26,  10,  -8]])

In [183]:
# Determinante de "A8_1" (DA8_1)
DA8_1 = np.linalg.det(A8_1)
DA8_1

-17304.0

In [186]:
# Lambda al cubo por "DA8"
DA8_lambda = (2**3)*DA8
DA8_lambda

-17303.999999999993

In [187]:
# La propiedad 8 se cumple. Por lo tanto, el "DA8_1" es igual a lambda =  2 por el "DA8".
print(f"El determiante de 'A8_1' = {DA8_1} es igual a lambda = 2 por el 'DA8' = {DA8_lambda}")

El determiante de 'A8_1' = -17304.0 es igual a lambda = 2 por el 'DA8' = -17303.999999999993


## Problema 5

Mejore el código descrito en clase para hallar el determinate de una matriz que contenga ceros en la matriz diagonal, utlizar condicionales

In [29]:
# Código a mejorar.
# Importar libreria NumPy
import numpy as np
vec = []
A = np.array([[3,4,2],
              [-2,3,5],
              [4,2,6]])
for i in range(0,(len(A)-1)):
    vec.append(A[i][i])
    A[i]=(1/A[i][i])*A[i]
    for j in range((i+1),len(A)):
        if (A[j][i]*A[(i)][i])>0:
            A[j]=A[j][i]*A[(i)]-A[j]            
        else:    
            A[j]=-A[j][i]*A[(i)]+A[j]           
vec.append(A[(len(A)-1)][(len(A)-1)]) 
det=np.prod(vec)
det

120

In [37]:
# Un intento de mejora en colaboración con un compañero externo.
'''
En resumen, este código implementa un algoritmo para calcular el determinante
de una matriz cuadrada utilizando la eliminación gaussiana, que consiste en 
transformar la matriz original en una matriz triangular superior y luego multiplicar
los elementos de la diagonal principal para obtener el determinante.
'''
# Importar libreria NumPy
import numpy as np
A = np.array([[3,4,2],
              [-2,3,5],
              [4,2,6]])
# Tamaño de la matriz
n = A.shape[0] 
# diagonal principal de la matriz
vec = [A[i,i] for i in range(n)]  
det = 1
signo = 1
for i, pivot in enumerate(vec[:-1]):
    # encontrar el índice del elemento de mayor magnitud debajo del pivote.
    k = i + 1 + np.argmax(np.abs(A[i+1:, i]))
    # intercambiar las filas i y k si el elemento de mayor magnitud no está debajo del pivote.
    if k != i+1:
        A[[i+1, k]] = A[[k, i+1]]
        signo *= -1
    # realizar eliminación Gaussiana en la columna i.
    A = A.astype(float)  # convertir la matriz a tipo de dato de punto flotante.
    for j in range(i+1, n):
        m = A[j,i] / A[i,i]
        A[j, i+1:] -= m * A[i, i+1:]
        A[j, i] = m
det *= np.prod(np.diag(A))
det *= signo
print(det)  # salida: 120.0

120.0


## Problema 6

Crear una función para hallar la solución de un sistema de ecuaciones mediante el método de Cramer

In [68]:
# Primero importamos la libreria Numpy
import numpy as np
# Detalles de los parámetros que se usaran
'''
Donde:
    - "A" será la matriz de coeficientes y
    - "b" el vector de términos independientes.
    - Además, la función para calcular la solución del
      sistema de ecuaciones mediante el método
      de Cramer se llamará "MCramer".
    - "dA" es el determiante de "A".
'''
# Empecemos definiendo la función
def MCramer(A,b):
    n = len(b)
    if (A.shape[0] != A.shape[1]) or (n != len(b)):
        return "A y b deben tener la misma cantidad de filas y A debe ser cuadrada"
    dA = np.linalg.det(A)
    if (dA == 0):
        return "El sistema no tiene solución"
    Soluciones = []
    for i in range(n):
        matriz_i = A.copy()
        matriz_i[:,i] = b
        det_i = np.linalg.det(matriz_i)
        Soluciones.append(det_i/dA)
    return Soluciones

Resolvamos el siguiente sistema de ecuaciones usando la función anteriormente creada.

$$
\begin{align*}
2x + 3y - z =& 8\\
4x - y + 2z =& 3 \\
x + y + 3z =& 14
\end{align*}
$$

In [69]:
# Usando la función "MCramer"
A = np.array([[2, 3, -1], 
              [4, -1, 2], 
              [1, 1, 3]])
b = np.array([8, 3, 14])
Soluciones = MCramer(A, b)
print(f"Las soluciones del sistema son:\n {Soluciones}")

Las soluciones del sistema son:
 [-1.6776703483224582e-16, 3.7999999999999967, 3.399999999999998]


## Problema 7

Craer un sistema de ecuaciones del orden que desee y verificar las siguientes propiedades

\begin{align}
& \text{ 1. Intercambia el orden de dos ecuaciones cualesquiera.}\\
& \text{ 2. Multiplica ambos lados de una ecuación por una constante distinta de cero.}\\
& \text{ 3. Suma un múltiplo distinto de cero de una ecuación a otra ecuación.}
\end{align}

In [ ]:
# A continuación creamos un sistema de ecuaciones con 3 ecuaciones y tres incógnitas

$$
\begin{align*}
2x + 3y + z =& 5\\
4x + y -3z =& 1 \\
x-y + 2z =& 3
\end{align*}
$$

In [27]:
# Importar la libreria NumPy
import numpy as np

In [28]:
# Creamos la matriz de coeficientes (A)
A = np.array([
    [2,3,1],
    [4,1,-3],
    [1,-1,2]
])

In [29]:
# Creamos un vector de los términos independientes
b = np.array(
[5,1,3]
)

In [30]:
# Resolvemos el sistema de ecuaciones usando la función "solve()", donde el primer 
# componente es la matriz "A" y el segundo es el vector "b".
x = np.linalg.solve(A,b)
# Ahora imprimiendo la solución del sistema:
print(f"Las soluciones del sistema son: {x}")

Las soluciones del sistema son: [1.05 0.55 1.25]


In [23]:
#------------------ 1. Intercambia el orden de dos ecuaciones cualesquiera ---------------------------#

In [37]:
'''
Propiedad 1: En este caso intercambiamos la primera fila con 
la tercera tanto en la matriz "A" y vector "b".
'''
A[[0,2]] = A[[2,0]] # Cambio de las filas en la matriz "A".
b[[0,2]] = b[[2,0]] # Cambio de las filas en el vector "b".
# Resolviendo el nuevo sistema de ecuaciones usando nuevamente la función "solve()"
solucion1 = np.linalg.solve(A,b)
print(f"La solución del nuevo sistema es: {solucion1}") # La solcuión no cambió.

La solución del nuevo sistema es: [1.05 0.55 1.25]


In [ ]:
#---------- 2. Multiplica ambos lados de una ecuación por una constante distinta de cero ---------------------#

In [45]:
'''
Propiedad 2: En este caso como nos pide multiplicar cualquier ecuación por una 
constante distinta de cero, se multiplicará a la segunda ecuación por 5. 
'''
A[1] = A[1]*5
b[1] = b[1]*5
# Resolviendo el nuevo sistema de ecuaciones usando nuevamente la función "solve()"
solucion2 = np.linalg.solve(A,b)
print(f"La solución del nuevo sistema es: {solucion2}") # La solución no cambió.

La solución del nuevo sistema es: [1.05 0.55 1.25]


In [ ]:
#---------- 3. Suma un múltiplo distinto de cero de una ecuación a otra ecuación ---------------------#

In [46]:
'''
Propiedad 3: En este caso vamos a sumar cuatro veces a la fila 2 en la matriz "A"
y el valor correspondiente en el vector "b" a la tercera fila.
'''
A[2] = A[2] + 4 * A[1]
b[2] = b[2] + 4 * b[1]
# Resolviendo el nuevo sistema de ecuaciones usando nuevamente la función "solve()"
solucion3 = np.linalg.solve(A,b)
print(f"La solución del nuevo sistema es: {solucion3}") # La solución no cambió.

La solución del nuevo sistema es: [1.05 0.55 1.25]


## Problema 8

Crear una matriz de orden 4X4 y hallar los valores propios y vectores propios, y comprobar que cumple la definición.

In [ ]:
''' 
Para crear una matriz de orden 4x4 en Python, utilizamos la biblioteca NumPy.
Luego, utilizamos la función "eig" para calcular los valores propios y vectores propios
de la matriz, y posteriormente comprobamos si cumplen con la definición. A continuación, se muestra un 
ejemplo:
'''

In [5]:
# Importar la libreria NumPy
import numpy as np

In [6]:
# Creamos una matriz de orden 4x4 (4 filas y 4 columnas)
Matriz4x4 = np.array([[2, -1, 0, 0], 
                      [-1, 2, -1, 0], 
                      [0, -1, 2, -1], 
                      [0, 0, -1, 2]])

In [7]:
# Calculamos los valores propios y vectores propios de la matriz
ValoresPropios, VectoresPropios = np.linalg.eig(Matriz4x4)

In [10]:
# Mostramos los valores propios y vectores propios
print("Valores propios:")
print(ValoresPropios)
print("Vectores propios:")
print(VectoresPropios)

Valores propios:
[3.61803399 2.61803399 0.38196601 1.38196601]
Vectores propios:
[[-0.37174803 -0.60150096 -0.37174803 -0.60150096]
 [ 0.60150096  0.37174803 -0.60150096 -0.37174803]
 [-0.60150096  0.37174803 -0.60150096  0.37174803]
 [ 0.37174803 -0.60150096 -0.37174803  0.60150096]]


In [11]:
# Comprobamos si se cumple la definición
for i in range(len(ValoresPropios)):
    EigVal = ValoresPropios[i]
    EigVec = VectoresPropios[:, i]
    # Comprobamos que A * x = lambda * x
    if np.allclose(Matriz4x4 @ EigVec, EigVal * EigVec):
        print(f"El vector propio {EigVec} corresponde al valor propio {EigVal}.")
    else:
        print("La definición no se cumple para el valor propio y vector propio dados.")

El vector propio [-0.37174803  0.60150096 -0.60150096  0.37174803] corresponde al valor propio 3.6180339887498922.
El vector propio [-0.60150096  0.37174803  0.37174803 -0.60150096] corresponde al valor propio 2.618033988749894.
El vector propio [-0.37174803 -0.60150096 -0.60150096 -0.37174803] corresponde al valor propio 0.3819660112501052.
El vector propio [-0.60150096 -0.37174803  0.37174803  0.60150096] corresponde al valor propio 1.381966011250106.


In [ ]:
'''
En este ejemplo, hemos creado una matriz de orden 4x4 con valores específicos
y hemos utilizado la función "eig" para calcular sus valores propios y vectores propios.
Luego, hemos comprobado si se cumple la definición para cada valor propio y vector propio,
utilizando la función "allclose" de NumPy para comparar los resultados. Si se cumple la definición,
el programa muestra el vector propio y valor propio correspondientes.
'''

In [ ]:
#-------------------------- FIN