In [1]:
import pandas as pd
import numpy as np

## Problema 1

Crear un Data Frame con columnas Nombre, Edad, Peso, sueldo de 10 personas, y poner en un vector los sueldos de todas la personas

In [2]:
data=pd.DataFrame({'Nombre':['Pedro','Pepe','Rosa', 'Carmen', 'Julio', 'Carlos', 'Roberto', 'Luis', 'María', 'Martín'],
                   'Edad':[20,18,25,26,30,30,45,50,50,36],
                   'Peso':[70,65,68,75,80,81,90,75,71,86],
                   'Sueldo':[2000,1800,3000,3200,3500,3100,4000,4500,4200,3600]
                  })

In [3]:
data

Nombre  Edad  Peso  Sueldo
0    Pedro    20    70    2000
1     Pepe    18    65    1800
2     Rosa    25    68    3000
3   Carmen    26    75    3200
4    Julio    30    80    3500
5   Carlos    30    81    3100
6  Roberto    45    90    4000
7     Luis    50    75    4500
8    María    50    71    4200
9   Martín    36    86    3600

In [4]:
suledos=np.array([data.Sueldo])
suledos

array([[2000, 1800, 3000, 3200, 3500, 3100, 4000, 4500, 4200, 3600]],
      dtype=int64)

## Problema 2

Crear una función con parámetros r y h, para hallar el volumen de un cilindro 

In [2]:
def VolCilindro(r,h):
    v=(np.pi)*(r**2)*h
    return('El volumen es', v)

In [3]:
VolCilindro(2,3)

('El volumen es', 37.69911184307752)

## Problema 3

Crear una función para encontrar los n-ésimos primeos términos de una serie de Fibonacci

In [7]:
def Fibonacci(n):
    n2=1
    n1=0
    l=[n1,n2]
    for i in range(0,n):
        f=l[i]+l[(i+1)]
        l.append(f)
    return(l)

In [8]:
Fibonacci(100)

[0,
 1,
 1,
 2,
 3,
 5,
 8,
 13,
 21,
 34,
 55,
 89,
 144,
 233,
 377,
 610,
 987,
 1597,
 2584,
 4181,
 6765,
 10946,
 17711,
 28657,
 46368,
 75025,
 121393,
 196418,
 317811,
 514229,
 832040,
 1346269,
 2178309,
 3524578,
 5702887,
 9227465,
 14930352,
 24157817,
 39088169,
 63245986,
 102334155,
 165580141,
 267914296,
 433494437,
 701408733,
 1134903170,
 1836311903,
 2971215073,
 4807526976,
 7778742049,
 12586269025,
 20365011074,
 32951280099,
 53316291173,
 86267571272,
 139583862445,
 225851433717,
 365435296162,
 591286729879,
 956722026041,
 1548008755920,
 2504730781961,
 4052739537881,
 6557470319842,
 10610209857723,
 17167680177565,
 27777890035288,
 44945570212853,
 72723460248141,
 117669030460994,
 190392490709135,
 308061521170129,
 498454011879264,
 806515533049393,
 1304969544928657,
 2111485077978050,
 3416454622906707,
 5527939700884757,
 8944394323791464,
 14472334024676221,
 23416728348467685,
 37889062373143906,
 61305790721611591,
 99194853094755497,
 16050

## Problema 4

Crear dos vectores de orden 10 y aplicar las propiedades mostradas en clase 

In [9]:
x=np.array([3,4,5,5,2,4,5,5,6,9])
x

array([3, 4, 5, 5, 2, 4, 5, 5, 6, 9])

In [10]:
y=np.array([2,1,4,5,5,4,5,9,6,8])
y

array([2, 1, 4, 5, 5, 4, 5, 9, 6, 8])

In [11]:
z=np.array([9,7,8,5,5,6,5,1,2,3])
z

array([9, 7, 8, 5, 5, 6, 5, 1, 2, 3])

#### Conmutativa

In [12]:
x+y

array([ 5,  5,  9, 10,  7,  8, 10, 14, 12, 17])

In [13]:
y+x

array([ 5,  5,  9, 10,  7,  8, 10, 14, 12, 17])

#### Asociativa

In [14]:
a1=x+y

In [15]:
a1+z

array([14, 12, 17, 15, 12, 14, 15, 15, 14, 20])

In [16]:
a2=y+z

In [17]:
x+a2

array([14, 12, 17, 15, 12, 14, 15, 15, 14, 20])

#### Elemento neutro

In [18]:
ceros=np.zeros(10)
ceros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [19]:
x+ceros

array([3., 4., 5., 5., 2., 4., 5., 5., 6., 9.])

In [20]:
ceros+x

array([3., 4., 5., 5., 2., 4., 5., 5., 6., 9.])

In [21]:
x

array([3, 4, 5, 5, 2, 4, 5, 5, 6, 9])

#### Elemento inverso de la suma

In [22]:
x+np.dot(-1,x)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Problema 5

Craer un Data Frame con 4 oraciones parecidas al ejemplo aplicativo de PLN y vectorizar

In [23]:
from sklearn.feature_extraction.text import  CountVectorizer
from sklearn.feature_extraction.text import  TfidfVectorizer

In [25]:
datos=pd.DataFrame({'Descripción':['Mario escribió la Casa Verde',
                                   'Gabriel escribió Cien Áños de Soledad',
                                   'César escribió Los Herados Negros',
                                   'Mario y Gabriel fueron amigos'
                                  ]})
datos

Descripción
0           Mario escribió la Casa Verde
1  Gabriel escribió Cien Áños de Soledad
2      César escribió Los Herados Negros
3          Mario y Gabriel fueron amigos

In [28]:
palabras=pd.DataFrame({'Descripción':['mario escribio Casa Verde',
                                   'gabriel escribio cien años Soledad',
                                   'cesar escribio heraldos negros',
                                   'mario gabriel fueron amigos'
                                  ]})
palabras

Descripción
0           mario escribio Casa Verde
1  gabriel escribio cien años Soledad
2      cesar escribio heraldos negros
3         mario gabriel fueron amigos

||amigos|años|casa|cesar|cien|escribio|fueron|gabriel|heraldos|mario|negros|soledad|verde|
|-|-|-|-|-|-|-|-|-|-|-|-|-|-|
|0|0|0|1|0|0|1|0|0|0|1|0|0|1|
|1|0|1|0|0|1|1|0|1|0|0|0|1|0|
|2|0|0|0|1|0|1|0|0|1|0|1|0|0|
|3|1|0|0|0|0|0|1|1|0|1|0|0|0|

In [29]:
contador=CountVectorizer()
vectorizador=TfidfVectorizer()


In [30]:
cantidad=contador.fit_transform(palabras.Descripción)
valores=vectorizador.fit_transform(palabras.Descripción)

In [32]:
print('palalabras')
print(vectorizador.get_feature_names())
print('cantidad')
print(cantidad)
print('Puntuaciones')
print(valores)

palalabras
['amigos', 'años', 'casa', 'cesar', 'cien', 'escribio', 'fueron', 'gabriel', 'heraldos', 'mario', 'negros', 'soledad', 'verde']
cantidad
  (0, 9)	1
  (0, 5)	1
  (0, 2)	1
  (0, 12)	1
  (1, 5)	1
  (1, 7)	1
  (1, 4)	1
  (1, 1)	1
  (1, 11)	1
  (2, 5)	1
  (2, 3)	1
  (2, 8)	1
  (2, 10)	1
  (3, 9)	1
  (3, 7)	1
  (3, 6)	1
  (3, 0)	1
Puntuaciones
  (0, 12)	0.5745795256791941
  (0, 2)	0.5745795256791941
  (0, 5)	0.3667466683744504
  (0, 9)	0.4530050977381881
  (1, 11)	0.4981971092712959
  (1, 1)	0.4981971092712959
  (1, 4)	0.4981971092712959
  (1, 7)	0.3927843233041577
  (1, 5)	0.3179927614076589
  (2, 10)	0.5417361046803605
  (2, 8)	0.5417361046803605
  (2, 3)	0.5417361046803605
  (2, 5)	0.3457831381910465
  (3, 0)	0.5552826649411127
  (3, 6)	0.5552826649411127
  (3, 7)	0.43779123108611473
  (3, 9)	0.43779123108611473


## Problema 6

Crear dos matrices de cualquier orden y aplicar las propiedades de producto de un escalar con un  vector

In [33]:
x=np.array([[1,2,3],[3,4,3],[3,5,3]])
x

array([[1, 2, 3],
       [3, 4, 3],
       [3, 5, 3]])

In [34]:
y=np.array([[3,2,1],[2,2,3],[3,6,3]])
y

array([[3, 2, 1],
       [2, 2, 3],
       [3, 6, 3]])

In [35]:
lam=3
beta=5

#### Asociativa

In [36]:
a=lam*beta

In [37]:
a*x

array([[15, 30, 45],
       [45, 60, 45],
       [45, 75, 45]])

In [38]:
b=beta*x

In [39]:
lam*b

array([[15, 30, 45],
       [45, 60, 45],
       [45, 75, 45]])

#### Distributiva por la izquierda

In [40]:
a=lam+beta

In [41]:
a*x

array([[ 8, 16, 24],
       [24, 32, 24],
       [24, 40, 24]])

In [42]:
lam*x+beta*x

array([[ 8, 16, 24],
       [24, 32, 24],
       [24, 40, 24]])

#### Distributiva por la derecha

In [43]:
a=lam+beta

In [44]:
x*a

array([[ 8, 16, 24],
       [24, 32, 24],
       [24, 40, 24]])

In [45]:
lam*x+beta*x

array([[ 8, 16, 24],
       [24, 32, 24],
       [24, 40, 24]])

#### distributiva por la derecha para la suma de vectores

In [46]:
a=np.dot(lam,(x+y))
a

array([[12, 12, 12],
       [15, 18, 18],
       [18, 33, 18]])

In [47]:
lam*x+lam*y

array([[12, 12, 12],
       [15, 18, 18],
       [18, 33, 18]])

## Problema 7

Hallar la norma Euclidiana y de Manhattan de un vector que usted cree conveniente

In [48]:
x=np.array([2,3,4,1,5,6,2,6,7,8,9])
x

array([2, 3, 4, 1, 5, 6, 2, 6, 7, 8, 9])

#### Norma Euclidiana

In [49]:
np.linalg.norm(x,2)

18.027756377319946

#### Norma de  Manhattan

In [50]:
np.linalg.norm(x, 1)

53.0

## Problema 8

Probar si  son ortogonales dos vectores que usted crea conveniente

In [51]:
x = np.array([[10],[0],[0]])
y = np.array([[0],[10],[0]])

cos_theta = (x.T@y)/(np.linalg.norm(x,2) * np.linalg.norm(y,2))
cos_theta

array([[0.]])

In [52]:
cos_inversa = np.arccos(cos_theta)
ángulo = cos_inversa * ((180)/np.pi)
ángulo

array([[90.]])

In [ ]:
#sí son ortogonales

## Problema 9

Aplicar las propiedades de la  Multiplicación matriz-matriz para las matrices que usted crea conveniente

In [53]:
A=np.array([[2,3,4,5],[1,2,4,6],[8,9,5,7]])
A

array([[2, 3, 4, 5],
       [1, 2, 4, 6],
       [8, 9, 5, 7]])

In [54]:
B=np.array([[3,1,4,6],[9,2,4,1],[4,5,5,6],[1,5,2,1]])
B

array([[3, 1, 4, 6],
       [9, 2, 4, 1],
       [4, 5, 5, 6],
       [1, 5, 2, 1]])

In [55]:
C=np.array([[30,1,4,6,6,7,9],[10,2,4,1,1,2,3],[0,5,5,6,0,1,2],[1,0,2,1,9,8,7]])
C

array([[30,  1,  4,  6,  6,  7,  9],
       [10,  2,  4,  1,  1,  2,  3],
       [ 0,  5,  5,  6,  0,  1,  2],
       [ 1,  0,  2,  1,  9,  8,  7]])

#### Asociativa

In [56]:
Z=A@B


In [57]:
Z@C

array([[2194,  410,  766,  721,  773,  886, 1053],
       [1878,  373,  688,  615,  655,  759,  906],
       [4914,  839, 1595, 1614, 1724, 1955, 2318]])

In [58]:
W=B@C

In [59]:
A@W

array([[2194,  410,  766,  721,  773,  886, 1053],
       [1878,  373,  688,  615,  655,  759,  906],
       [4914,  839, 1595, 1614, 1724, 1955, 2318]])

#### Multipliación por un escalar

In [60]:
lam=15

In [61]:
Z=A@B

In [62]:
np.dot(lam,Z)

array([[ 810,  795,  750,  660],
       [ 645,  825,  660,  570],
       [1980, 1290, 1605, 1410]])

In [63]:
W=np.dot(lam,A)

In [64]:
W@B

array([[ 810,  795,  750,  660],
       [ 645,  825,  660,  570],
       [1980, 1290, 1605, 1410]])

#### Distributiva

In [65]:
C=np.array([[30,1,4,6],[1,1,2,3],[6,0,1,2],[1,0,2,1]])
C

array([[30,  1,  4,  6],
       [ 1,  1,  2,  3],
       [ 6,  0,  1,  2],
       [ 1,  0,  2,  1]])

In [66]:
W=B+C

In [67]:
A@W

array([[146,  58,  78,  78],
       [105,  58,  68,  64],
       [418, 103, 176, 186]])

In [68]:
A@B+A@C

array([[146,  58,  78,  78],
       [105,  58,  68,  64],
       [418, 103, 176, 186]])

#### Transpuesta del producto

In [69]:
np.transpose(A@B)

array([[ 54,  43, 132],
       [ 53,  55,  86],
       [ 50,  44, 107],
       [ 44,  38,  94]])

In [70]:
np.transpose(B)@np.transpose(A)

array([[ 54,  43, 132],
       [ 53,  55,  86],
       [ 50,  44, 107],
       [ 44,  38,  94]])

## Problema 10

Hallar la inversa de una matriz no singular que usted crea conveniente de orden 10X10

In [71]:
A=np.arange(1,20,2)
A

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [72]:
mat=[]
k=-300
for i in range(0,10):
    k=k+6
    mat.append(np.linspace(k,100,10))

In [73]:
mat

[array([-294.        , -250.22222222, -206.44444444, -162.66666667,
        -118.88888889,  -75.11111111,  -31.33333333,   12.44444444,
          56.22222222,  100.        ]),
 array([-288.        , -244.88888889, -201.77777778, -158.66666667,
        -115.55555556,  -72.44444444,  -29.33333333,   13.77777778,
          56.88888889,  100.        ]),
 array([-282.        , -239.55555556, -197.11111111, -154.66666667,
        -112.22222222,  -69.77777778,  -27.33333333,   15.11111111,
          57.55555556,  100.        ]),
 array([-276.        , -234.22222222, -192.44444444, -150.66666667,
        -108.88888889,  -67.11111111,  -25.33333333,   16.44444444,
          58.22222222,  100.        ]),
 array([-270.        , -228.88888889, -187.77777778, -146.66666667,
        -105.55555556,  -64.44444444,  -23.33333333,   17.77777778,
          58.88888889,  100.        ]),
 array([-264.        , -223.55555556, -183.11111111, -142.66666667,
        -102.22222222,  -61.77777778,  -21.33333333,

In [131]:
#vemos que sea no singular

In [74]:
np.linalg.det(mat)

1.5717859565655175e-107

In [ ]:
#calculamos la inversa

In [75]:
np.linalg.inv(mat)

array([[-4.88036306e+13,  3.07646517e+13,  4.10108744e+13,
         9.13116007e+12, -2.52814613e+12, -4.40073602e+13,
         3.11556743e+13, -3.00936293e+13,  6.64278754e+12,
         6.72761819e+12],
       [-6.92566718e+11, -4.61959468e+12, -2.39088332e+13,
        -4.57821098e+12,  3.00818797e+12,  2.56125709e+13,
         3.81142661e+13,  3.48129581e+12, -7.75657144e+11,
        -3.56414581e+13],
       [ 2.92252625e+13,  1.72831304e+13, -2.40911092e+13,
        -2.07344876e+13, -2.01742635e+13,  3.23174283e+13,
        -4.80560559e+13,  7.51397055e+12, -7.50588535e+12,
         3.42220097e+13],
       [ 3.51494108e+13, -4.09307581e+13,  1.12493887e+13,
        -1.33468907e+13, -5.57388687e+12, -3.70412153e+11,
        -1.10772596e+13,  4.79657079e+13, -2.09115629e+13,
        -2.15373703e+12],
       [ 6.30015997e+13, -4.26032063e+12, -1.96856195e+13,
        -4.06934074e+13,  9.98971734e+12, -4.96792561e+13,
        -2.41907861e+13,  2.49742933e+12,  6.53738855e+13,
        -2.

## Problema 11 

Crear una función que encuentre los n primeros números perfectos 

In [76]:
#creando una función de divisores menores que el numero
def divisoresM(N):        
    divisores=[]
    for i in range(1,N):
        if N%i==0:
            divisores.append(i)
    return(divisores)        
        

In [77]:
divisoresM(2047)

[1, 23, 89]

In [78]:
#hallando los primeros números perfectos entre 1 y 10000,
#OJO, tener cuidado y no subir la cifra, por que el bucle se demorará un montón
perfecto=[]
for i in range(1,10000):
    if sum(divisoresM(i))==i:
        perfecto.append(i)
        print(perfecto)
    
    

[6]
[6, 28]
[6, 28, 496]
[6, 28, 496, 8128]
