## Problema 1

Crear un Data Frame con columnas Nombre, Edad, Peso, sueldo de 10 personas, y poner en un vector los sueldos de todas la personas

In [1]:
import pandas as pd

Datos = {
    "Nombre": ["Luis", "Maria", "Carla", "Pedro", "Lucia", "Marcelo", "Pavel", "Martha", "Carolina", "Tania"],
    "Edad": [25,31,26,19,27,34,41,21,43,28],
    "Peso": [67,72,80,75,69,70,81,69,67,79],
    "Sueldo":[2500, 3200, 5000, 3000, 2700, 1800, 2100, 3500, 4200, 3100],
}
Datos = pd.DataFrame(Datos)

In [2]:
Datos

Nombre  Edad  Peso  Sueldo
0      Luis    25    67    2500
1     Maria    31    72    3200
2     Carla    26    80    5000
3     Pedro    19    75    3000
4     Lucia    27    69    2700
5   Marcelo    34    70    1800
6     Pavel    41    81    2100
7    Martha    21    69    3500
8  Carolina    43    67    4200
9     Tania    28    79    3100

## Problema 2

Crear una función con parámetros r y h, para hallar el volumen de un cilindro 

In [20]:
# Definamos una función
import numpy as np
def VolumenCilindro(r,h):
    '''
    Esta función calcula el volumen
    de un cilindro.
    '''
    v = np.pi*r**2*h
    return v

In [21]:
VolumenCilindro(3,5)

141.3716694115407

## Problema 3

Crear una función para encontrar los n-ésimos términos de una serie de Fibonacci

In [17]:
# Definimos la función
def fibonacci(n):
    '''
    Esta función busca el n-ésimo término 
    de una serie de Fibonacci
    Por ejemplo:
        1, 1, 2, 3, 5, 8, 13, 21, 34, ...
        Termino 1: 1
        Termino 2: 1
        Termino 3: 2
        Termino 4: 3
        .
        .
        .
    '''
    if (n<0):
        print('--------------------------')
        print("Ingresa un número positivo")
        print('--------------------------')
    elif (n==0):
        return (0)
    elif (n==1 or n==2):
        return (1)
    else:
        return (fibonacci(n-1) + 
                fibonacci(n-2))

In [22]:
fibonacci(4)

3

## Problema 4

Crear dos vectores de orden 10 y aplicar las propiedades mostradas en clase 

In [23]:
# Creamos dos vectores
Vector1 = np.array([1,2,3,4,5,6,7,8,9,10])
Vector2 = np.array([2,4,6,8,10,12,14,16,18,20])

In [24]:
Vector1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
Vector2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [27]:
# Suma de vectores
SumaVectores = Vector1 + Vector2
SumaVectores

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [28]:
# Multiplicación de vectores
MultVectores = Vector1*Vector2
MultVectores

array([  2,   8,  18,  32,  50,  72,  98, 128, 162, 200])

## Problema 5

Craer un Data Frame con 4 oraciones parecidas al ejemplo aplicativo de PLN y vectorizar

In [78]:
# Importamos las librerias
import pandas as pd
from sklearn.feature_extraction.text import  CountVectorizer
from sklearn.feature_extraction.text import  TfidfVectorizer

In [80]:
Datos = pd.DataFrame({
    "Descripción": ["Mi casa es verde", 
                  "Verde es la montaña", 
                  "La montaña es alta",
                  "Alta es la casa de la montaña"]
})
Oraciones

Descripción
0                Mi casa es verde
1             Verde es la montaña
2             La montania es alta
3  Alta es la casa de la montania

In [85]:
Palabras = pd.DataFrame({
    "Descripción": ["Casa Verde", "Verde Montaña",  "Montaña Alta", "Alta Casa Montaña"]})
Palabras

Descripción
0         Casa Verde
1      Verde Montaña
2       Montaña Alta
3  Alta Casa Montaña

In [86]:
Contador = CountVectorizer()
Vectorizador = TfidfVectorizer()

In [87]:
Cantidades = Contador.fit_transform(Palabras.Descripción)
Valores = Vectorizador.fit_transform(Palabras.Descripción)

In [92]:
print('Palabras')
#print(Vectorizador.get_feature_names())
print('Cantiades')
print(Cantidades)
print('Valores')
print(Valores)

Palabras
Cantiades
  (0, 1)	1
  (0, 3)	1
  (1, 3)	1
  (1, 2)	1
  (2, 2)	1
  (2, 0)	1
  (3, 1)	1
  (3, 2)	1
  (3, 0)	1
Valores
  (0, 3)	0.7071067811865475
  (0, 1)	0.7071067811865475
  (1, 2)	0.6292275146695526
  (1, 3)	0.7772211620785797
  (2, 0)	0.7772211620785797
  (2, 2)	0.6292275146695526
  (3, 0)	0.6136667440107333
  (3, 2)	0.4968161174826459
  (3, 1)	0.6136667440107333


## Problema 6

Crear dos matrices de cualquier orden y aplicar las propiedades de producto de un escalar con un  vector

In [32]:
# Importar libreria
import numpy as np
# Crear dos matrices
A = np.array([[1, 2], [4, 5], [12, 43]]) # matriz de orden 3x3
B = np.array([[7, 8], [9, 10], [11, 12]]) # matriz de orden 3x3

k = 2 # Escalar "k=2"
D = k * A + k * B
print('----------------------')
print('RESULTADO:')
print(' ')
print("D =\n", D)
print('----------------------')

----------------------
RESULTADO:
 
D =
 [[ 16  20]
 [ 26  30]
 [ 46 110]]
----------------------


## Problema 7

Hallar la norma Euclidiana y de Manhattan de un vector que usted cree conveniente

* Norma Euclidiana

$$||x||=\sqrt{ \sum_{i=1}^{n} x_{i}^{2}}=\sqrt{ X^{T}X }$$

In [19]:
import numpy as np
NE = np.array([3,4,5])

In [20]:
np.linalg.norm(NE,2)

7.0710678118654755

* Norma de Manhattan

$$||x||=\sum_{i=1}^{n} |x_{i}|$$

In [21]:
import numpy as np
NM = np.array([3,4,5,6])

In [23]:
np.linalg.norm(NM, 1)

18.0

## Problema 8

Probar si  son ortogonales dos vectores que usted crea conveniente

In [18]:
import numpy as np
u = np.array([3,5])
v = np.array([6,8])

El coseno del ángulo que forman dos vectores es igual al producto escalar entre los dos vectores dividido por el producto de los módulos de los dos vectores.

$$\cos(\alpha)= x = \dfrac{\vec{u}\cdot\vec{v}}{|\vec{u}|\cdot|\vec{v}|}$$

In [19]:
x = (u @ v) / (np.linalg.norm(u, 2) * np.linalg.norm(v,2))
x
print(f"El valor de x es: {coseno_alpha}")

El valor de x es: 0.9946917938265513


* Arco coseno
$$\alpha=\arccos(x)$$

In [20]:
# "Alpha" es un ángulo trigonométrico en grados sexagesimales 
Alpha= np.arccos(x)
Alpha
print(f"El valor de alfa es: {coseno_alpha_invesa}")

El valor de alfa es: 0.10308160852270018


* Conversión a radianes
$$\alpha^{°}*\frac{180}{\pi}$$

In [21]:
# "Beta" es un ángulo en radianes 
Beta = x * ((180)/np.pi)
Beta

56.99164170255842

Por lo tanto, el vector $"u"$ y $"v"$ no son ortogonales, dado que el ángulo que forman entre ellos no es igual a $90°$ o $\pi/2$.

## Problema 9

Aplicar las propiedades de la  Multiplicación matriz-matriz para las matrices que usted crea conveniente

In [28]:
import numpy as np
# Creamos una matriz M de orden 3x3
M = np.array([[1,4,7],
              [2,5,3],
              [4,6,9]])
# Creamos una matriz N de orden 3x3
N = np.array([[3,6,9],
              [1,3,5],
              [2,8,4]])

In [29]:
print(f"Salida de la matriz M:\n {M}")

Salida de la matriz M:
 [[1 4 7]
 [2 5 3]
 [4 6 9]]


In [30]:
print(f"Salida de la matriz N:\n {N}")

Salida de la matriz N:
 [[3 6 9]
 [1 3 5]
 [2 8 4]]


In [40]:
# Opción 1 de calcular el producto de matrices
OP1 = M@N
print(f"El producto de MxN es: \n {OP1}")

El producto de MxN es: 
 [[ 21  74  57]
 [ 17  51  55]
 [ 36 114 102]]


In [38]:
# Opción 2 de calcular el producto de matrices
OP2 = np.dot(M,N)
print(f"El producto de MxN es: \n {OP2}")

El producto de MxN es: 
 [[ 21  74  57]
 [ 17  51  55]
 [ 36 114 102]]


## Problema 10

Hallar la inversa de una `matriz no singular` que usted crea conveniente de orden 10X10

Recordemos un poco de teoría
* Matriz no singular
$$
|A| \neq 0
$$
* La inversa de una matriz no singular
$$
A^{-1} = \dfrac{1}{|A|}Adj(A) = \dfrac{1}{|A|}\left(Cof(A)\right){'}
$$


In [45]:
import numpy as np
# Creamos una matriz de orden 10 por 10
A = np.array(
    [
        [1,4,5,7,8,2,6,4,0,4],
        [9,6,0,1,8,1,0,4,8,2],
        [7,4,5,7,2,2,1,4,8,4],
        [2,4,6,2,9,7,0,0,6,4],
        [3,9,5,7,8,2,0,4,0,4],
        [5,4,5,9,8,1,0,9,8,3],
        [8,4,3,7,5,2,7,4,8,4],
        [1,4,5,7,6,2,0,4,8,4],
        [7,4,1,7,8,5,9,4,1,6],
        [0,6,0,6,3,9,0,4,8,4],
    ]
)

In [44]:
A

array([[1, 4, 5, 7, 8, 2, 6, 4, 0, 4],
       [9, 6, 0, 1, 8, 1, 0, 4, 8, 2],
       [7, 4, 5, 7, 2, 2, 1, 4, 8, 4],
       [2, 4, 6, 2, 9, 7, 0, 0, 6, 4],
       [3, 9, 5, 7, 8, 2, 0, 4, 0, 4],
       [5, 4, 5, 9, 8, 1, 0, 9, 8, 3],
       [8, 4, 3, 7, 5, 2, 7, 4, 8, 4],
       [1, 4, 5, 7, 6, 2, 0, 4, 8, 4],
       [7, 4, 1, 7, 8, 5, 9, 4, 1, 6],
       [0, 6, 0, 6, 3, 9, 0, 4, 8, 4]])

In [60]:
# Veamos los métodos que nos proporciona la libreria "NumPy"
dir(np)
dir(np.linalg)

['LinAlgError',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_umath_linalg',
 'cholesky',
 'cond',
 'det',
 'eig',
 'eigh',
 'eigvals',
 'eigvalsh',
 'inv',
 'linalg',
 'lstsq',
 'matrix_power',
 'matrix_rank',
 'multi_dot',
 'norm',
 'pinv',
 'qr',
 'slogdet',
 'solve',
 'svd',
 'tensorinv',
 'tensorsolve',
 'test']

In [56]:
# Calculamos el determinate de la matriz "A"
detA = np.linalg.det(A)
detA

-55352599.99999995

In [57]:
# Calculamos la inversa de la matriz "A"
InversaA = np.linalg.inv(A)
InversaA
print(f"La inversa de la matriz no singular 'A' es: \n {InversaA}")

La inversa de la matriz no singular 'A' es: 
 [[-0.20586328 -0.06648808 -0.01818075  0.06204081  0.08592623  0.08599126
   0.09238908 -0.09123669  0.0674041  -0.05743094]
 [ 0.1933851   0.11153745  0.06435745 -0.06922746  0.04642167 -0.13173437
   0.01174695 -0.06736291 -0.14521074  0.08152737]
 [ 0.30867536  0.05605778  0.2355549   0.04570589 -0.09897494 -0.03728678
  -0.10895401 -0.16800035 -0.14721433  0.00675083]
 [-0.68475418 -0.38576659 -0.45455382  0.09851859  0.34895055  0.23732797
   0.48577967  0.11750335  0.12918013 -0.09032703]
 [-0.24399497 -0.08203582 -0.26537839  0.08380889  0.10405437  0.10870817
   0.14873     0.09150797  0.07647092 -0.07394746]
 [-0.06657082 -0.09159259 -0.03140145  0.11128149  0.02276027  0.10378266
   0.0651564  -0.20064076 -0.0028076   0.07158558]
 [ 0.25919982  0.07078518  0.04757095 -0.03700928 -0.09933987 -0.08111489
   0.04058548 -0.08654799 -0.09854092  0.04879583]
 [ 0.61123543  0.2872931   0.3995834  -0.14085066 -0.30871359 -0.05639482
  -0.

## Problema 11 

Crear una función que encuentre los n primeros números perfectos 

In [17]:
def NumeroPerfecto(x):
    '''
    Un número es perfecto si es igual a la suma de sus divisores excepto él mismo.
    La función NumeroPerfecto toma como argumento "x" el número de números perfectos
    que deseamos encontrar. Utiliza un ciclo while que continúa hasta que se hayan
    encontrado "x" números perfectos. Para cada número, se encuentran sus divisores y
    se suman. Si la suma de los divisores es igual al número, entonces es un número
    perfecto y se agrega a la lista de números perfectos.
    '''
    NumeroPerfecto = []
    Numero = 2
    Contar = 0
    while Contar < x:
        Divisores = [i for i in range(1, Numero) if Numero % i == 0]
        if sum(Divisores) == Numero:
            NumeroPerfecto.append(Numero)
            Contar += 1
        Numero += 1
    return NumeroPerfecto

In [18]:
print(NumeroPerfecto(3))

[6, 28, 496]
