In [1]:
import pandas as pd
import numpy as np

## Problema 1

Crear una matriz de orden 3x3 y hallar el determiante con numpy, además aplicar el método de cofactores utilizando el jupyter como calculadora, es decir hacerlo celda por celda

In [2]:
A = np.array([[3,4,2],[-2,3,5],[4,2,6]])
A

array([[ 3,  4,  2],
       [-2,  3,  5],
       [ 4,  2,  6]])

#### utilizando np.linalg.det(A)

In [3]:
np.linalg.det(A)

119.99999999999997

#### utilizando las celdas como calculadora

In [4]:
#creando una función para extraer la sub matriz eliminado las filas y
#columnas correspondientes a los valores de la primera columna
def menor(M, f):
    vec=[]    
    for i in range(0,len(M)):
        if i!=f:
            vec.append(i)
            r=M[1:len(M),vec]
    return(r)

In [5]:
A

array([[ 3,  4,  2],
       [-2,  3,  5],
       [ 4,  2,  6]])

In [6]:
menor(A,0)

array([[3, 5],
       [2, 6]])

### creando una función para hallar el determinate de 2x2

In [7]:
def det22(n):
    d=(n[0][0]*n[1][1])-(n[1][0]*n[0][1])
    return(d)

In [8]:
det22(menor(A,0))

8

#### hallando el determinante

In [9]:
A[0][0]*det22(menor(A,0))-A[0][1]*det22(menor(A,1))+A[0][2]*det22(menor(A,2))

120

## Problema 2

Hacer una función que resuelva el problema anterior

In [10]:
A=[[1,4,6,7,8],[6,2,3,4,7],[3,2,1,7,9],[8,6,2,3,2],[5,7,9,8,3]]
A

[[1, 4, 6, 7, 8],
 [6, 2, 3, 4, 7],
 [3, 2, 1, 7, 9],
 [8, 6, 2, 3, 2],
 [5, 7, 9, 8, 3]]

In [11]:
#creado una funcion para hallar los cofacores 
def cofactor(m, i, j):
    a=[]
    for row in (m[: i] + m[i+1:]):
        b=row[: j] + row[j+1:]
        a.append(b)
    return(a)    

In [12]:
#creando una función para hallar el determinante 
def deterCOFAC(mat):
    if(len(mat) == 2):
        value = mat[0][0] * mat[1][1] - mat[1][0] * mat[0][1]
        return value    
    Sum = 0    
    for colum in range(len(mat)):        
        signo = (-1) ** (colum)
        sub_det = deterCOFAC(cofactor(mat, 0, colum))        
        Sum += (signo * mat[0][colum] * sub_det)    
    return Sum

In [13]:
deterCOFAC(A)

5238

In [14]:
np.linalg.det(A)

5237.999999999992

In [15]:
A =([[3,4,2],[-2,3,5],[4,2,6]])
A

[[3, 4, 2], [-2, 3, 5], [4, 2, 6]]

In [16]:
np.linalg.det(A)

119.99999999999997

In [17]:
deterCOFAC(A)

120

## Problema 3

Hacer una función que resuelva el problema uno con el método de Sarrus 

In [18]:
A =([[3,4,2],[-2,3,5],[4,2,6]])
A

[[3, 4, 2], [-2, 3, 5], [4, 2, 6]]

In [19]:
#utilizando las funciones de python
np.linalg.det(A)

119.99999999999997

In [20]:
#creando una función
def sarrus(A):
    P=(A[0][0]*A[1][1]*A[2][2]+A[0][1]*A[1][2]*A[2][0]+A[1][0]*A[2][1]*A[0][2])-(A[2][0]*A[1][1]*A[0][2]+A[2][1]*A[1][2]*A[0][0]+A[1][0]*A[0][1]*A[2][2])
    return(P)

In [21]:
sarrus(A)

120

## Problema 4

Replicar las 8 propiedades vistas en clase para los determinantes mediante un ejemplo 

\begin{align}
&\text{1) } |A^{T}|=|A|\\
&\text{2) Si todos los elementos de una fila (o columna) son cero, entonces el determinante es cero.}\\
&\text{3) Si todos los elementos de una fila (o columna) son proporcionales (idénticos) a los elementos de alguna otra fila (o columna), entonces el determinante es cero.}\\
&\text{4) El intercambio de dos filas (o columnas) cualesquiera del determinante cambia su signo.}\\
&\text{5) si} B \text{ es una Matriz formada sumando el múltiplo de cualquier fila a otra fila, entonces } det (X) = det (B)\\ 
&\text{6) } \begin{vmatrix}
{\lambda a_{11}\quad\cdots\quad \lambda a_{1n}}\\
{a_{21}\quad\cdots\quad a_{2n}}\\
{\vdots \quad \vdots}\\
{a_{n1}\quad\cdots\quad a_{nn}}\\
\end{vmatrix}=
\lambda \begin{vmatrix}
{a_{11}\quad\cdots\quad a_{1n}}\\
{a_{21}\quad\cdots\quad a_{2n}}\\
{\vdots \quad \vdots}\\
{a_{n1}\quad\cdots\quad a_{nn}}\\
\end{vmatrix}, \quad
\begin{vmatrix}
{\lambda a_{11}\quad\cdots\quad  a_{1n}}\\
{\lambda a_{21}\quad\cdots\quad a_{2n}}\\
{\vdots \quad \vdots}\\
{\lambda a_{n1}\quad\cdots\quad a_{nn}}\\
\end{vmatrix}=
\lambda \begin{vmatrix}
{a_{11}\quad\cdots\quad a_{1n}}\\
{a_{21}\quad\cdots\quad a_{2n}}\\
{\vdots \quad \vdots}\\
{a_{n1}\quad\cdots\quad a_{nn}}\\
\end{vmatrix}, \quad
\begin{vmatrix}
{\lambda a_{11}\quad\cdots\quad \lambda a_{1n}}\\
{\lambda a_{21}\quad\cdots\quad  \lambda a_{2n}}\\
{\vdots \quad \vdots}\\
{\lambda a_{n1}\quad\cdots\quad \lambda a_{nn}}\\
\end{vmatrix}=
\lambda^{n} \begin{vmatrix}
{a_{11}\quad\cdots\quad a_{1n}}\\
{a_{21}\quad\cdots\quad a_{2n}}\\
{\vdots \quad \vdots}\\
{a_{n1}\quad\cdots\quad a_{nn}}\\
\end{vmatrix} \\
&\text{7) } \begin{vmatrix}
{a_{11}+b_{11}\quad\cdots\quad  a_{1n}}\\
{a_{21}+b_{21}\quad\cdots\quad a_{2n}}\\
{\vdots \quad \vdots}\\
{a_{n1}+b_{n1}\quad\cdots\quad a_{nn}}\\
\end{vmatrix}=
\begin{vmatrix}
{a_{11}\quad\cdots\quad  a_{1n}}\\
{a_{21}\quad\cdots\quad a_{2n}}\\
{\vdots \quad \vdots}\\
{a_{n1}\quad\cdots\quad a_{nn}}\\
\end{vmatrix}+
\begin{vmatrix}
{b_{11}\quad\cdots\quad  a_{1n}}\\
{b_{21}\quad\cdots\quad a_{2n}}\\
{\vdots \quad \vdots}\\
{b_{n1}\quad\cdots\quad a_{nn}}\\
\end{vmatrix}\\
&\text{8) } \begin{vmatrix}
{a_{11}\quad 0 \quad\cdots\quad  0}\\
{a_{21}\quad a_{22}\quad\cdots\quad 0}\\
{\vdots \quad \vdots}\\
{a_{n1}\quad a_{n2}\quad\cdots\quad a_{nn}}\\
\end{vmatrix}=
\begin{vmatrix}
{a_{11} \quad a_{12}\quad\cdots\quad  a_{1n}}\\
{0 \quad a_{22} \quad\cdots\quad a_{2n}}\\
{\vdots \quad \vdots}\\
{0\quad \quad 0\cdots\quad a_{nn}}\\
\end{vmatrix}= a_{11}\times a_{22}\times \cdots a_{nn}
\end{align}


#### solución 1

In [22]:
A =([[3,4,2],[-2,3,5],[4,2,6]])
A

[[3, 4, 2], [-2, 3, 5], [4, 2, 6]]

In [23]:
np.linalg.det(A)

119.99999999999997

In [24]:
B=np.transpose(A)
B

array([[ 3, -2,  4],
       [ 4,  3,  2],
       [ 2,  5,  6]])

In [25]:
np.linalg.det(B)

119.99999999999997

#### solución 2

In [26]:
A =([[0,0,0],[-2,3,5],[4,2,6]])
A

[[0, 0, 0], [-2, 3, 5], [4, 2, 6]]

In [27]:
np.linalg.det(A)

0.0

#### solución 3

In [28]:
A =([[3,8,6],[4,9,8],[5,12,10]])

In [29]:
np.linalg.det(A)

0.0

#### solución 4

In [30]:
A =([[3,4,2],[-2,3,5],[4,2,6]])
A

[[3, 4, 2], [-2, 3, 5], [4, 2, 6]]

In [31]:
np.linalg.det(A)

119.99999999999997

In [32]:
A =([[3,4,2],[4,2,6],[-2,3,5]])
A

[[3, 4, 2], [4, 2, 6], [-2, 3, 5]]

In [33]:
np.linalg.det(A)

-119.99999999999997

In [34]:
A =([[4,2,6],[3,4,2],[-2,3,5]])
A

[[4, 2, 6], [3, 4, 2], [-2, 3, 5]]

In [35]:
np.linalg.det(A)

119.99999999999997

#### solución 5

In [36]:
A =([[3,4,2],[-2,3,5],[4,2,6]])
A

[[3, 4, 2], [-2, 3, 5], [4, 2, 6]]

In [37]:
np.linalg.det(A)

119.99999999999997

In [38]:
B =([[7,6,8],[-2,3,5],[4,2,6]])
B

[[7, 6, 8], [-2, 3, 5], [4, 2, 6]]

In [39]:
np.linalg.det(B)

119.99999999999997

#### Solución 6

In [40]:
A = np.array([[3,4,2],[-2,3,5],[4,2,6]])
A

array([[ 3,  4,  2],
       [-2,  3,  5],
       [ 4,  2,  6]])

In [41]:
np.linalg.det(A)

119.99999999999997

In [42]:
lanm=3

In [43]:
A[0]=lanm*A[0]

In [44]:
A

array([[ 9, 12,  6],
       [-2,  3,  5],
       [ 4,  2,  6]])

In [45]:
np.linalg.det(A)

360.00000000000006

#### Solución 7

In [46]:
A = np.array([[3,4,2],[-2,3,5],[4,2,6]])
A

array([[ 3,  4,  2],
       [-2,  3,  5],
       [ 4,  2,  6]])

In [47]:
A[:,0]=A[:,0]+np.array([3,4,5])

In [48]:
A

array([[6, 4, 2],
       [2, 3, 5],
       [9, 2, 6]])

In [49]:
np.linalg.det(A)

133.99999999999997

In [50]:
A1=np.array([[3,4,2],[-2,3,5],[4,2,6]])
A1

array([[ 3,  4,  2],
       [-2,  3,  5],
       [ 4,  2,  6]])

In [51]:
d1=np.linalg.det(A1)
d1

119.99999999999997

In [52]:
A2=np.array([[3,4,2],[4,3,5],[5,2,6]])
A2

array([[3, 4, 2],
       [4, 3, 5],
       [5, 2, 6]])

In [53]:
d2=np.linalg.det(A2)
d2

13.999999999999996

In [54]:
d1+d2

133.99999999999997

#### solucion 8

In [55]:
A = np.array([[3,2,1],[0,3,5],[0,0,6]])
A


array([[3, 2, 1],
       [0, 3, 5],
       [0, 0, 6]])

In [56]:
np.linalg.det(A)

54.00000000000001

## Problema 5

Mejor el código descrito en clase para hallar el determinate de una matriz que contenga ceros en la matriz diagonal, utlizar condicionales

In [57]:
vec=[]
#A = np.array([[0,4,2],[-2,3,5],[4,2,6]],dtype=float)
#A=np.array([[0,4,6,7],[6,2,3,4],[3,2,1,7],[8,6,2,3]],dtype=float)
A=np.array([[0,4,6,7,8],[6,2,3,4,7],[3,2,1,7,9],[8,6,2,3,2],[5,7,9,8,3]],dtype=float) 
for i in range(0,(len(A)-1)):
    if(A[i][i]==0.0):            #la condición si es que es igual a cero  
        for k in range(i,len(A)):
            if (A[k][k]!=0):
                break
        fil=np.copy(A[i,:])
        A[i,:]=A[k,:]
        A[k,:]=fil
        vec.append(-1)
        vec.append((A[i][i]))
        A[i]=(1/A[i][i])*A[i]
        for j in range((i+1),len(A)):
            if(A[j][i]==0.0):  
                for l in range(j,len(A)):
                    if (A[l][l]!=0):
                        break
                fil2=np.copy(A[j,:])
                A[j,:]=A[l,:]
                A[l,:]=fil2
                vec.append(-1)
                if (A[j][i]*A[(i)][i])>0:
                    A[j]=A[j][i]*A[(i)]-A[j]            
                else:    
                    A[j]=-A[j][i]*A[(i)]+A[j]            
            else:                
                if (A[j][i]*A[(i)][i])>0:
                    A[j]=A[j][i]*A[(i)]-A[j]            
                else:    
                    A[j]=-A[j][i]*A[(i)]+A[j]            
        
    else:
        vec.append((A[i][i]))
        A[i]=(1/A[i][i])*A[i]
        for j in range((i+1),len(A)):
            if(A[j][i]==0.0):  
                for l in range(j,len(A)):
                    if (A[l][l]!=0):
                        break
                fil2=np.copy(A[j,:])
                A[j,:]=A[l,:]
                A[l,:]=fil2
                vec.append(-1)
                if (A[j][i]*A[(i)][i])>0:
                    A[j]=A[j][i]*A[(i)]-A[j]            
                else:    
                    A[j]=-A[j][i]*A[(i)]+A[j]            
            else:                
                if (A[j][i]*A[(i)][i])>0:
                    A[j]=A[j][i]*A[(i)]-A[j]            
                else:    
                    A[j]=-A[j][i]*A[(i)]+A[j]            
vec.append((A[(len(A)-1)][(len(A)-1)])) 
det=np.prod(vec) 

In [58]:
det

6174.0

In [59]:
A=np.array([[0,4,6,7,8],[6,2,3,4,7],[3,2,1,7,9],[8,6,2,3,2],[5,7,9,8,3]],dtype=float)
A

array([[0., 4., 6., 7., 8.],
       [6., 2., 3., 4., 7.],
       [3., 2., 1., 7., 9.],
       [8., 6., 2., 3., 2.],
       [5., 7., 9., 8., 3.]])

In [60]:
#con las funciones de python
np.linalg.det(A)

6173.999999999996

## Problema 6

Craer una función para hallar la solución de un sistema de ecuaciones mediante el método de Cramer

In [61]:
A = np.array([[8, 3, -2], [-4, 7, 5], [3, 4, -12]])
b = np.array([9, 15, 35])

In [62]:
#Utilizando las funciones de python
x = np.linalg.solve(A, b)
x

array([-0.58226371,  3.22870478, -1.98599767])

In [63]:
#con el método de Cramer
def CRAMER(A,b):
    sol=[]
    for i in range(0,len(b)):
        B=np.copy(A)
        B[:,i]=b
        s=np.linalg.det(B)/np.linalg.det(A)
        sol.append(s)
    return(sol)    

In [64]:
CRAMER(A,b)

[-0.5822637106184368, 3.2287047841306897, -1.9859976662777132]

## Problema 7

Craer un sistema de ecuaciones del orden que desee y verificar las siguientes propiedades

\begin{align}
& \text{ 1. Intercambia el orden de dos ecuaciones cualesquiera.}\\
& \text{ 2. Multiplica ambos lados de una ecuación por una constante distinta de cero.}\\
& \text{ 3. Suma un múltiplo distinto de cero de una ecuación a otra ecuación.}
\end{align}

#### 1)

In [65]:
#Utilizando las funciones de python

A = np.array([[8, 3, -2], [-4, 7, 5], [3, 4, -12]])
b = np.array([9, 15, 35])
x = np.linalg.solve(A, b)
x

array([-0.58226371,  3.22870478, -1.98599767])

In [66]:
# intercambiando las primera ecuación con la segunda ecuación

In [67]:
A = np.array([[-4, 7, 5],[8, 3, -2], [3, 4, -12]])
b = np.array([15, 9, 35])
x = np.linalg.solve(A, b)
x

array([-0.58226371,  3.22870478, -1.98599767])

#### 2)

In [68]:
#multiplicando por 18 a la segunda ecuación

In [69]:
lam=18

In [70]:
A = np.array([[8, 3, -2], np.dot(lam,[-4, 7, 5]), [3, 4, -12]])
b = np.array([9, lam*15, 35])
x = np.linalg.solve(A, b)
x

array([-0.58226371,  3.22870478, -1.98599767])

#### 3)

In [71]:
#Suma un múltiplo distinto de cero de una ecuación a otra ecuación

In [72]:
#sumado al la primera ecuacion 2 veces la tercera 

In [73]:
A = np.array([[8+2*3, 3+2*4, -2+2*(-12)], [-4, 7, 5], [3, 4, -12]])
b = np.array([9+2*35, 15, 35])
x = np.linalg.solve(A, b)
x

array([-0.58226371,  3.22870478, -1.98599767])

## Problema 8

Craer una matriz de oderden 4X4 y hallar los valores propios y vectores propios, y comprobar que cumple la definición

In [74]:
A=np.array([[0,4,6,7],[6,2,3,4],[3,2,1,7],[8,6,2,3]],dtype=float)
A

array([[0., 4., 6., 7.],
       [6., 2., 3., 4.],
       [3., 2., 1., 7.],
       [8., 6., 2., 3.]])

#### Hallando los eigenvalores y eigenvectores

In [75]:
w, v = np.linalg.eig(A)

In [76]:
# Eigen valores
w

array([16.39670648+0.j        , -4.33667148+0.j        ,
       -3.0300175 +2.00258772j, -3.0300175 -2.00258772j])

In [77]:
#Eigen vectores 
v

array([[-0.51653663+0.j        ,  0.67707337+0.j        ,
        -0.38594904+0.16861566j, -0.38594904-0.16861566j],
       [-0.46497328+0.j        , -0.55572464+0.j        ,
         0.42501604+0.20881108j,  0.42501604-0.20881108j],
       [-0.42479261+0.j        ,  0.31119514+0.j        ,
        -0.59701774+0.j        , -0.59701774-0.j        ],
       [-0.58012154+0.j        , -0.3686453 +0.j        ,
         0.38768671-0.30272136j,  0.38768671+0.30272136j]])

#### comprobando

$ A \nu  $

In [78]:
np.dot(A,v[:,0])

array([-8.46949954+0.j, -7.62403033+0.j, -6.96519981+0.j, -9.51208254+0.j])

$\lambda \nu$

In [79]:
np.dot(w[0],v[:,0])

array([-8.46949954+0.j, -7.62403033+0.j, -6.96519981+0.j, -9.51208254+0.j])