# Ejercicio 1

Creamos listas

In [1]:
Lista1 = [2, 4, 6 ,8 , 10, 12, 14, 16, 18, 20]

In [2]:
Lista1

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]

In [4]:
Lista2 = list([1,3,5,7,9,11,13,15,17,19])

In [5]:
Lista2

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]

In [10]:
Lista1[0], Lista1[3], Lista1[6], Lista1[8]

(2, 8, 14, 18)

In [12]:
Lista2[1], Lista2[3], Lista2[6], Lista2[9]

(3, 7, 13, 19)

In [29]:
Lista1[0] = 100 # Remplazamos el elemento 2 por 100

In [30]:
Lista1 

[100, 4, 6, 8, 10, 12, 14, 16, 18, 20]

# Ejercicio 2

Creamos tuplas

In [13]:
Tupla1 = (2, 4, 6, 8, 10, 12, 14, 16, 18, 20)

In [14]:
Tupla1

(2, 4, 6, 8, 10, 12, 14, 16, 18, 20)

In [18]:
Tupla2 = tuple((1,3,5,7,9,11,13,15,17,19))

In [20]:
Tupla2

(1, 3, 5, 7, 9, 11, 13, 15, 17, 19)

In [21]:
Tupla1[2]

6

In [22]:
Tupla2[5]

11

In [26]:
Tupla1[2] = 33 # Genero un error porque las tuplas son inmutables

TypeError: 'tuple' object does not support item assignment

# Ejercicio 3

Utilizamos el array

In [58]:
import numpy as np
# Utilizamos listas
Matriz1 = np.array(
    [
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15]
    ]
)
Matriz1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [59]:
type(Matriz1)

numpy.ndarray

In [60]:
Matriz1.shape

(3, 5)

In [61]:
Matriz1.size

15

In [68]:
Matriz1[2,:] # muestra la tercera fila y todas las columnas

array([11, 12, 13, 14, 15])

In [70]:
Matriz1[:,3] # muestra todas las filas de la columna 4

array([ 4,  9, 14])

In [62]:
# Utilizamos tuplas
Matriz2 = np.array(
    (
    (1,2,3,4),
    (6,7,8,9),
    (11,12,13,14)
    )
)
Matriz2

array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [11, 12, 13, 14]])

In [63]:
type(Matriz2)

numpy.ndarray

In [64]:
Matriz2.shape

(3, 4)

In [65]:
Matriz2.size

12

# Ejercicio 4

Indicando el tipo de dato del array

In [48]:
Array1 = np.array([[2,3,5], [4,7,9]], dtype = float)
Array1

array([[2., 3., 5.],
       [4., 7., 9.]])

In [50]:
Array2 = np.array([[2.5,3,5.4], [4,7.5,9.1]], dtype = int)
Array2

array([[2, 3, 5],
       [4, 7, 9]])

# Ejercicio 5

Usando el `linspace`

In [52]:
import numpy as np

In [ ]:
# Generar 10 números entre 1000 y 10,000

In [56]:
GenNum10 = np.linspace(1000,10000,10)

In [57]:
GenNum10

array([ 1000.,  2000.,  3000.,  4000.,  5000.,  6000.,  7000.,  8000.,
        9000., 10000.])

In [ ]:
# La multiplicación de elementos uno a uno de dos vectores o listas

In [ ]:
## Opción 1

In [73]:
Vector1_op1 = [1, 2, 3, 4]
Vector2_op1 = [2, 3, 4, 5]

Resultado1 = [x * y for x, y in zip(Vector1_op1, Vector2_op1)]

print(Resultado1)

[2, 6, 12, 20]


In [ ]:
## opción 2

In [74]:
import numpy as np

Vector1_op2 = np.array([1, 2, 3, 4])
Vector2_op2 = np.array([2, 3, 4, 5])

Resultado2 = np.multiply(Vector1_op2, Vector2_op2)

print(Resultado2)

[ 2  6 12 20]


In [ ]:
#------ RETO CUMPLIDO. 